'use client';
import { createContext, useContext, useEffect, useState } from 'react';
import { weekdayComboCopy } from './weekdayComboCopy';

export type Language = 'sv' | 'en';

const sv = {
  common: {
    back: 'Tillbaka',
    continue: 'Fortsätt',
    confirm: 'Bekräfta',
    cancel: 'Avbryt',
    skip: 'Hoppa över',
    processing: 'Behandlar…',
    loading: 'Laddar…',
    currency: 'kr',
    done: 'Klart',
    yes: 'Ja',
    no: 'Nej',
    callStaff: 'Hämta personal',
    staffCalled: 'Personal är på väg',
    stillThere: 'Är du kvar?',
    stillThereDesc: 'Tryck var som helst för att fortsätta, annars börjar vi om.',
    imHere: 'Jag är kvar',
    exit: 'Avsluta',
    language: 'Språk',
    switchLanguage: 'Byt språk till',
  },
  exitFlow: {
    title: 'Vill du avsluta?',
    description: 'Dina val på den här enheten tas bort. En bokning eller betalning som redan är klar påverkas inte.',
    confirm: 'Avsluta och gå till start',
    stay: 'Fortsätt här',
  },
  progress: {
    booking: 'Bokning',
    safety: 'Säkerhet',
    extras: 'Tillägg',
    payment: 'Betalning',
    done: 'Klar',
  },
  buyProgress: {
    entry: 'Entré',
    addons: 'Tillägg',
    payment: 'Betalning',
    safety: 'Säkerhet',
    done: 'Klar',
  },
  idle: {
    tap: 'Tryck för att börja',
    line1: 'Välkommen till',
    line2: 'JumpYard',
  },
  start: {
    eyebrowKiosk: 'Kiosk',
    eyebrowPark: 'Park-QR',
    eyebrowSms: 'SMS-länk',
    title: 'Välkommen!',
    subtitle: 'Samma incheckning oavsett hur du kom hit.',
    cta: 'Starta',
  },
  choice: {
    title: 'Vad vill du göra?',
    haveBooking: 'Jag har en bokning',
    haveBookingDesc: 'Hitta din bokning och checka in',
    buyTickets: 'Köp entré',
    buyTicketsDesc: 'Köp entré och fortsätt till check-in',
  },
  lookup: {
    title: 'Hitta din bokning',
    description: 'Skriv in bokningsnummer, mejl eller telefonnummer för att hitta din bokning.',
    placeholder: 'Bokningsnummer, mejl eller telefon',
    cta: 'Sök',
    notFound: 'Vi hittade ingen bokning idag.',
    tryAgain: 'Kontrollera uppgiften eller hämta personal.',
    paymentRequired: 'Bokningen har kvar att betala.',
    paymentRequiredDesc: 'Hämta personal så hjälper vi dig vidare.',
    wrongDate: 'Bokningen gäller ett annat datum.',
    wrongDateDesc: 'Kontrollera datumet eller hämta personal.',
    noRedeemableTickets: 'Bokningen saknar biljetter att checka in.',
    noRedeemableTicketsDesc: 'Hämta personal så kontrollerar vi bokningen.',
    serviceUnavailable: 'Vi kunde inte nå bokningssystemet.',
    serviceUnavailableDesc: 'Försök igen eller hämta personal.',
    lookupFailed: 'Något gick fel vid sökningen.',
    scanning: 'Skannar…',
  },
  buy: {
    selectTicket: 'Välj biljett',
    selectJumpTime: 'Välj hopptid',
    sectionEntry: 'Entré',
    sectionFamily: 'Familj',
    sectionCombo: weekdayComboCopy.sv.name,
    comboPeople: '2 personer',
    comboDuration: '60 min',
    comboPizza: '1 pizza',
    comboSeason: weekdayComboCopy.sv.availability,
    comboPackageNote: '2 personer',
    entry60: '60 min entré',
    entry90: '90 min entré',
    entry120: '120 min entré',
    family60: '60 min familj',
    family90: '90 min familj',
    family120: '120 min familj',
    perPersonNote: 'Per person',
    familyNote: '4 hoppare, 1 över 18',
    howMany: 'Hur många?',
    quantityJumpers: 'Antal hoppare',
    quantityPackages: 'Antal familjepaket',
    quantityComboPackages: 'Antal combo-paket',
    total: 'Totalt',
    toPay: 'Att betala',
    selectTime: 'Välj starttid',
    selectTimeToday: 'Idag',
    selectTimeDesc: 'Välj när ni vill börja hoppa.',
    startTimeLabel: 'Starttid',
    todaySuffix: 'idag',
    loadingAvailabilityTitle: 'Hämtar tillgängliga platser',
    loadingAvailabilityDesc: 'Vi kontrollerar kapacitet för',
    loadingAvailabilityGeneric: 'Vi kontrollerar kapacitet i Roller.',
    spotsLeft: 'platser kvar',
    spotsFull: 'Fullbokat',
    maxReached: 'Max',
    contactTitle: 'Din kontakt',
    contactDesc: 'Vi skickar bekräftelse och påminnelser.',
    emailLabel: 'E-post',
    emailPlaceholder: 'gäst@exempel.se',
    creating: 'Skapar bokning…',
    confirmCreate: 'Bekräfta & fortsätt',
    skipContact: 'Hoppa över',
    availabilityFailed: 'Vi kunde inte hämta lediga tider.',
    retryAvailability: 'Försök igen',
    noProductsAvailableTitle: 'Inga produkter tillgängliga',
    noProductsAvailableDesc: 'Det finns inga bokningsbara produkter för den valda tiden.',
    chooseAnotherTime: 'Välj en annan tid',
    spotsAvailable: 'Ledigt',
    firstNameLabel: 'Förnamn',
    lastNameLabel: 'Efternamn',
    phoneLabel: 'Telefon',
    phonePlaceholder: '0700000000',
    quoting: 'Räknar pris…',
    quoteFailed: 'Vi kunde inte räkna ut priset.',
    draftFailed: 'Vi kunde inte reservera bokningen.',
    unavailableProductFallback: 'Produkten',
    unavailableProductPrefix: 'är inte tillgänglig kl.',
    unavailableProductAction: 'Gå tillbaka till tillägg och ta bort valet eller välj en annan tid.',
    reviewTitle: 'Sammanställning',
    reviewDesc: 'Här är din entré, dina tillägg och totalen innan betalning.',
    jumpTimeLabel: 'Hopptid',
    jumpersLabel: 'Hoppare',
    createDraft: 'Gå till betalning',
    pendingTitle: 'Betalning väntar',
    pendingDesc: 'Bokningen är reserverad i Playground. Betalningssteget kopplas in när Roller-betalningen är godkänd.',
    draftStatus: 'Status',
    paymentPending: 'Väntar på betalning',
    paymentTitle: 'Betala',
    paymentSetupTitle: 'Förbereder betalning',
    paymentMethodTitle: 'Betalning',
    paymentStarting: 'Startar betalning',
    paymentReadyDesc: 'Betalningen laddas för',
    paymentReceived: 'Betalning mottagen',
    paymentReceivedDesc: 'Vi väntar på bekräftelse från betalningen.',
    paymentApprovedTitle: 'Betalning klar',
    paymentApprovedDesc: 'Vi synkar bokningen. Roller skickar bekräftelse och kvitto till e-posten på bokningen.',
    paymentFailedTitle: 'Betalningen stoppades',
    paymentFailedDesc: 'Betalningen kunde inte slutföras. Dina val finns kvar och du kan välja ett annat betalsätt.',
    paymentRecoveryTitle: 'Vi kan inte bekräfta betalningen ännu',
    paymentRecoveryDescription: 'Betala inte igen för samma köp. Kontrollera status igen om en stund. Om problemet kvarstår hjälper vi dig att kontrollera köpet på plats när du kommer till JumpYard.',
    paymentRetryMethod: 'Välj ett annat betalsätt',
    paymentCheckStatus: 'Kontrollera betalningen',
    paymentChecking: 'Vi kontrollerar betalningen',
    paymentBlockedTitle: 'Betalning saknas',
    paymentBlockedDesc: 'Betalningspaketet kunde inte startas för den här bokningen.',
    paymentMissingJwt: 'Bokningen saknar betalningstoken från Roller.',
    paymentMissingConfig: 'Bokningen saknar betalningskonfiguration från Roller.',
    paymentUnknownResult: 'Betalningen är mottagen men inte slutligt bekräftad.',
    paymentSyncing: 'Betalning genomförd',
    paymentSyncLoader: 'Hämtar bokningen...',
    paymentSyncFailed: 'Betalningen är klar men bokningen har inte hunnit synkas.',
    paymentSyncFallback: 'Kontrollera igen om en stund. Om problemet kvarstår hjälper vi dig att kontrollera köpet på plats när du kommer till JumpYard.',
    paymentRetrySync: 'Hämta bokningen igen',
    giftCardLabel: 'Presentkort',
    giftCardPlaceholder: 'Ange presentkortsnummer',
    giftCardHelp: 'Valfritt. Presentkortet kontrolleras av Roller innan bokningen reserveras.',
    giftCardApplied: 'Applicerat',
    giftCardRejected: 'Ej godkänt',
    giftCardErrorFallback: 'Presentkortet kunde inte användas.',
    giftCardFixHint: 'Kontrollera numret eller ta bort presentkortet för att fortsätta.',
    clipCardLabel: 'Klippkort',
    clipCardPlaceholder: 'Ange klippkortskod',
    clipCardHelp: 'Valfritt. Gäller klippkort som 10-, 20- eller 30-kort. Roller kontrollerar vilka entréprodukter koden täcker.',
    clipCardApplied: 'Applicerat',
    clipCardRejected: 'Ej godkänt',
    clipCardErrorFallback: 'Klippkortskoden kunde inte användas.',
    clipCardFixHint: 'Kontrollera koden eller ta bort den för att fortsätta.',
    paymentOptionsTitle: 'Lägg till presentkort eller klippkort',
    paymentOptionsApplyGiftCard: 'Applicera presentkort',
    paymentOptionsApplyClipCard: 'Applicera klippkort',
    paymentOptionsApplyBoth: 'Applicera presentkort och klippkort',
    paymentOptionsApplyChanges: 'Applicera ändring',
    paymentOptionsUpdateRequired: 'Applicera presentkortet eller klippkortet innan du går till betalning.',
    paymentCodeReady: 'Redo att applicera',
    paymentCodeDone: 'Klart',
    paymentCodeMaxLength: 'Max 32 tecken',
    originalTotal: 'Ordinarie total',
    noPaymentTitle: 'Bokning klar',
    noPaymentDesc: 'Presentkortet eller klippkortet täcker hela beloppet. Vi hämtar bokningen och fortsätter check-in.',
    noPaymentStatus: 'Ingen kortbetalning behövs',
  },
  buyRecovery: {
    title: 'Vi hittade din senaste check-in.',
    description: 'Fortsätt där du var.',
    checking: 'Hämtar bokningen',
    failedTitle: 'Vi hittade din senaste check-in.',
    failedDescription: 'Bokningen är sparad här, men vi kunde inte hämta den just nu. Försök igen eller börja om.',
    completedUnavailableTitle: 'Vi kan inte visa din tidigare bokning',
    completedUnavailableDescription: 'Du hade redan slutfört bokningen, men vi kan inte hämta den just nu. Försök igen för att visa den, eller gör en ny bokning.',
    unsafeDescription: 'Vi hittade en sparad check-in, men den saknar bokningsnummer. Börja om så skapar vi en ny säker väg.',
    retry: 'Försök igen',
    startOver: 'Börja om',
  },
  booking: {
    ref: 'Bokning',
    today: 'Idag',
    date: 'Datum',
    time: 'Tid',
    duration: 'Längd',
    guest: 'Gäst',
    jumpers: 'Hoppare',
    tickets: 'Biljetter',
    addons: 'Tillägg',
    none: 'Inga',
    paidInFull: 'Betald',
    notPaid: 'Obetald',
    title: 'Din bokning',
    subtitle: 'Ser det rätt ut? Då kör vi.',
    product: 'Produkt',
    cta: 'Ja, starta incheckning',
    startingSession: 'Startar incheckning…',
    paymentRequiredCta: 'Betalning krävs',
    paymentRequiredHint: 'Betalning byggs i en kommande ticket. Hämta personal tills vidare.',
    partiallyPaid: 'Delvis betald',
    checkInAtRegisterCta: 'Checka in i kassan',
    checkInAtRegisterHint: 'Den här bokningen behöver checkas in i kassan.',
    sessionStartFailed: 'Vi kunde inte starta incheckningen. Försök igen eller hämta personal.',
    sessionPaymentRequired: 'Bokningen har kvar att betala. Hämta personal så hjälper vi dig vidare.',
    sessionWrongDate: 'Bokningen gäller ett annat datum. Hämta personal så kontrollerar vi bokningen.',
    sessionAlreadyRedeemed: 'Biljetterna verkar redan vara använda. Hämta personal så kontrollerar vi bokningen.',
    sessionNotFresh: 'Vi behöver uppdatera bokningen innan incheckning. Hämta personal tills vidare.',
    timeHint: 'Tar ca 1–2 min. Nästa steg: säkerhetsvideo.',
  },
  safetyVideo: {
    title: 'Säkerhetsgenomgång',
    description: 'Titta på videon tillsammans med alla som ska hoppa.',
    buyTitle: 'Säkerhetsgenomgång',
    buyDescription: 'Titta på videon tillsammans med alla som ska hoppa.',
    play: 'Spela upp',
    playing: 'Videon spelas…',
    watchFull: 'Titta hela videon',
    done: 'Bekräfta säkerhetsreglerna',
    buyDone: 'Bekräfta säkerhetsreglerna',
    replay: 'Se videon igen',
    durationBadge: 'ca 15 sek',
  },
  safetyAttest: {
    title: 'Säkerhetsregler',
    description: 'Bekräfta varje regel innan du fortsätter.',
    buyTitle: 'Redo för entrén',
    buyDescription: 'Bekräfta säkerhetsreglerna så kan personalen checka in er.',
    ageRulesTitle: 'Åldersregler',
    ageRules: {
      adultInArea35: '3–5 år: vuxen måste medfölja i aktivitetsområdet.',
      adultInVenue610: '6–10 år: får hoppa själv om ansvarig vuxen finns i lokalen.',
      canJumpAlone11: '11 år och uppåt: får hoppa själv.',
    },
    safetyRulesTitle: 'Säkerhetsregler',
    rules: {
      onePerTrampoline: 'Endast en person per trampolin – risk för krock och okontrollerbar studs.',
      avoidEdgePadding: 'Undvik kantskydden – risk att stuka foten.',
      landOnBackOrBottom: 'Landa alltid på rumpa eller rygg i foampit och airbag. Andra landningar kan leda till allvarliga skador.',
      tricksWithinAbility: 'Gör bara tricks och volter som du klarar av.',
      noRunning: 'Spring inte i parken – risk för krock och fall.',
    },
    finalAttest: 'Jag intygar att samtliga i min bokning har tagit del av reglerna och förstått dem.',
    cta: 'Jag förstår, fortsätt',
    readyForStaffProcessing: 'G\u00f6r redo f\u00f6r personal...',
    readyForStaffFailed: 'Vi kunde inte g\u00f6ra incheckningen redo f\u00f6r personal. F\u00f6rs\u00f6k igen eller h\u00e4mta personal.',
    paymentConfirmationWaiting: 'Betalningen \u00e4r genomf\u00f6rd. Vi v\u00e4ntar p\u00e5 att bokningssystemet bekr\u00e4ftar bokningen, det kan ta upp till n\u00e5gon minut.',
    paymentConfirmationDelayed: 'Bokningen är ännu inte bekräftad. Betala inte igen. Kontrollera igen om en stund. Om problemet kvarstår hjälper vi dig på plats när du kommer till JumpYard.',
    paymentConfirmationRetry: 'Kontrollera igen',
  },
  addons: {
    title: 'Tillägg',
    choices: {
      preview: 'Testläge · testpriser · inga riktiga köp',
      socksTitle: 'Godkända hoppsockor',
      socksBenefit: 'Bra grepp. Krävs för alla hoppare.',
      ownSocks: 'Vi har egna godkända hoppsockor',
      socksRequired: 'Lägg till hoppsockor eller bekräfta att ni har med godkända hoppsockor.',
      bottleTitle: 'Vattenflaska',
      bottleEnvironment: 'Inga engångsmuggar av miljöskäl.',
      ownBottle: 'Vi har egen vattenflaska',
      bottleRequired: 'Lägg till en vattenflaska eller bekräfta att ni har med egen.',
      lockBenefit: 'Lås in dina saker medan du hoppar.',
      coffeeBenefit: 'En god paus mellan hoppen.',
      skyRiderBenefit: 'Se parken från ovan i vår höghöjdsbana.',
      recommended: 'Rekommenderas',
      included: '{count} ingår redan',
      quantity: 'Antal att lägga till',
      perPair: 'per par',
      add: 'Lägg till',
      remove: 'Ta bort',
      unavailableRequired: 'Kan inte köpas här just nu. Har ni inte med egna, fråga personalen.',
    },
    description: 'Välj till extra, hoppa över det du inte vill ha.',
    loading: 'H\u00e4mtar till\u00e4gg',
    socksSectionTitle: 'Godkända hoppstrumpor',
    socksHelp: 'Alla som hoppar behöver godkända hoppstrumpor.',
    socksAlreadyHave: 'Vi har redan godkända hoppstrumpor.',
    socksAddPrompt: 'Lägg till de strumpor ni behöver.',
    socksRecommendedCount: 'Rekommenderat antal',
    socksSelectedCount: 'Valt',
    waterBottleSectionTitle: 'Vattenflaska',
    waterBottleHelp: 'Har du med egen vattenflaska? Tyvärr kan vi inte dela ut engångsmuggar av miljöskäl.',
    waterBottleAlreadyHave: 'Vi har med egen vattenflaska.',
    alreadyInBooking: 'Ingår redan',
    total: 'Tillägg totalt',
    perJumper: 'per hoppare',
    each: 'st',
    eachLong: 'styck',
    perPerson: 'per person',
    connectedValueProp: 'Mest valt tillägg',
    unsupported: 'Kommer senare',
    unsupportedSelection: 'Det tillägget kan inte skapas automatiskt ännu.',
    contactTitle: 'Kontakt för tillägget',
    contactDesc: 'Roller kräver kontaktuppgifter för den separata tilläggsbokningen.',
    quoteFailed: 'Vi kunde inte räkna ut tillägget.',
    draftFailed: 'Vi kunde inte reservera tillägget.',
    reviewTitle: 'Kontrollera tillägg',
    reviewDesc: 'Priset hämtas direkt från bokningssystemet.',
    createDraft: 'Gå till betalning',
    paymentTitle: 'Betala tillägg',
    paymentApprovedTitle: 'Betalning klar',
    paymentApprovedDesc: 'Tillägget är betalt. Roller skickar bekräftelse och kvitto till e-posten på bokningen.',
    pendingTitle: 'Betalning väntar',
    pendingDesc: 'Tillägget är reserverat som en separat Playground-bokning. Betalningssteget kopplas in när Roller-betalningen är godkänd.',
    products: {
      skyriderLabel: 'SkyRider',
      skyriderDesc: 'Linbane-upplevelsen. Kräver min 100 cm.',
      connectedLabel: 'Connected',
      connectedDesc: 'Spåra hopp, tävla på topplistor, få highlight-klipp.',
      coffeeLabel: 'Bryggkaffe',
      coffeeDesc: 'Kaffe åt de vuxna medan barnen hoppar.',
      extraPersonLabel: 'Extra person',
      extraPersonDesc: 'Lägg till en till hoppare.',
      lockLabel: 'Hänglås',
      lockDesc: 'Hänglås till skåpen.',
      socksLabel: 'Strumpor',
      socksDesc: 'Hoppstrumpor, obligatoriska.',
      waterBottleLabel: 'Vattenflaska',
      waterBottleDesc: 'Köp till en flaska eller bekräfta att ni har med egen.',
    },
  },
  skyrider: {
    title: 'Innan SkyRider',
    description: 'Kolla höjdkravet och när SkyRider passar bäst.',
    infoLabel: 'SkyRider-information',
    requirementTitle: 'Minst 100 cm',
    requirementText: 'Alla som åker SkyRider behöver vara minst 100 cm.',
    timingTitle: 'Passar bäst efter hopptiden',
    timingText: 'Vi rekommenderar att SkyRider görs efter hoppasset.',
    confirmCheckbox: 'Jag bekräftar att alla SkyRider-åkare är minst 100 cm.',
    removeSkyRider: 'Ta bort SkyRider',
  },
  connected: {
    title: 'Connected-profiler',
    description: 'Varje Connected-band kopplas till en profil. Skriv namn så personalen vet vem som får vilket band.',
    profile: 'Profil',
    namePlaceholder: 'Namn',
    avatar: 'Ikon',
    confirm: 'Bekräfta profiler',
  },
  payment: {
    title: 'Betalning',
    description: 'Håll kortet mot terminalen när du är redo.',
    booking: 'Bokning',
    items: 'Vad du betalar för',
    total: 'Totalt',
    pay: 'Betala',
    afterPaymentHint: 'Efter betalning fortsätter du till entrén.',
    baseProduct: 'Bokning',
    addonsLabel: 'Tillägg',
  },
  confirm: {
    title: 'Redo för entrén',
    subtitle: 'Hämta armband hos personalen.',
    onsiteSubtitle: 'Hämta armband hos personalen.',
    smsSubtitle: 'Gå till personalen när ni kommer till parken.',
    kioskSubtitle: 'Ta utskriften och visa den när ni hämtar armband.',
    pickupCode: 'Bokning',
    handoffTitle: 'Visa vid entrén',
    handoffCode: 'Handoff-kod',
    qrHelp: 'Visa QR-koden för personalen. Det går också bra med namn, telefon eller e-post.',
    entryTicketFallback: 'Entré',
    staffHandout: 'Att hämta',
    otherAddons: 'Övrigt i bokningen',
    wristbands: 'Armband',
    connectedBands: 'Connected-band',
    complete: 'Klart & nästa gäst',
    done: 'Gör en ny bokning',
    showStaffNote: 'Visa personalen',
    alreadyCheckedInTitle: 'Redan incheckad',
    alreadyCheckedInSubtitle: 'Den här bokningen är redan slutförd.',
    alreadyCheckedInHelp: 'Hämta personal om något inte stämmer.',
  },
  print: {
    title: 'Klart, gå till banan!',
    subtitle: 'Ditt kvitto skrivs ut.',
    printing: 'Skriver ut…',
  },
  present: {
    eyebrow: 'Visa vid entrén',
    title: 'Redo för parken',
    instruction: 'Gå till personalen för att få armband.',
    startOver: 'Börja om',
  },
  extend: {
    loading: 'Laddar förlängning…',
    view: {
      title: 'Förläng din session',
      subtitle: '+30 minuter extra hopptid.',
      currentEnd: 'Nuvarande sluttid',
      newEnd: 'Ny sluttid',
      price: 'Pris',
      cta: 'Betala',
    },
    pay: {
      title: 'Betala förlängning',
      subtitle: '+30 min för',
      swish: 'Swish',
      card: 'Kort',
    },
    qr: {
      eyebrow: 'Bandbyte',
      title: '+30 minuter bekräftat',
      newEndPrefix: 'Ny sluttid:',
      nextStepLabel: 'Nästa steg',
      nextStepText: 'Gå till kassan eller personalen för att få ett nytt band med uppdaterad sluttid.',
    },
    error: {
      title: 'Vi kunde inte ladda förlängningen',
      expired: 'Länken har gått ut. Hämta personal.',
      already: 'Den här bokningen är redan förlängd.',
      generic: 'Något gick fel. Hämta personal.',
    },
  },
};

const en: typeof sv = {
  common: {
    back: 'Back',
    continue: 'Continue',
    confirm: 'Confirm',
    cancel: 'Cancel',
    skip: 'Skip',
    processing: 'Processing…',
    loading: 'Loading…',
    currency: 'kr',
    done: 'Done',
    yes: 'Yes',
    no: 'No',
    callStaff: 'Call staff',
    staffCalled: 'Staff is on the way',
    stillThere: 'Are you still there?',
    stillThereDesc: 'Tap anywhere to continue, otherwise we restart.',
    imHere: "I'm here",
    exit: 'Exit',
    language: 'Language',
    switchLanguage: 'Switch language to',
  },
  exitFlow: {
    title: 'Do you want to exit?',
    description: 'Your choices on this device are removed. A booking or payment that is already complete is not affected.',
    confirm: 'Exit and go to start',
    stay: 'Stay here',
  },
  progress: {
    booking: 'Booking',
    safety: 'Safety',
    extras: 'Extras',
    payment: 'Payment',
    done: 'Done',
  },
  buyProgress: {
    entry: 'Entry',
    addons: 'Add-ons',
    payment: 'Payment',
    safety: 'Safety',
    done: 'Done',
  },
  idle: {
    tap: 'Tap to start',
    line1: 'Welcome to',
    line2: 'JumpYard',
  },
  start: {
    eyebrowKiosk: 'Kiosk',
    eyebrowPark: 'Park QR',
    eyebrowSms: 'SMS Link',
    title: 'Welcome!',
    subtitle: 'Same check-in whichever way you arrived.',
    cta: 'Start',
  },
  choice: {
    title: 'What would you like to do?',
    haveBooking: 'I have a booking',
    haveBookingDesc: 'Find your booking and check in',
    buyTickets: 'Buy entry',
    buyTicketsDesc: 'Buy entry and continue to check-in',
  },
  lookup: {
    title: 'Find your booking',
    description: 'Enter booking number, email, or phone number to find your booking.',
    placeholder: 'Booking number, email, or phone',
    cta: 'Search',
    notFound: "We couldn't find a booking today.",
    tryAgain: 'Check the details or call staff.',
    paymentRequired: 'This booking still has payment due.',
    paymentRequiredDesc: 'Please call staff so we can help you continue.',
    wrongDate: 'This booking is for another date.',
    wrongDateDesc: 'Check the date or call staff.',
    noRedeemableTickets: 'This booking has no tickets to check in.',
    noRedeemableTicketsDesc: 'Please call staff so we can check the booking.',
    serviceUnavailable: "We couldn't reach the booking system.",
    serviceUnavailableDesc: 'Try again or call staff.',
    lookupFailed: 'Something went wrong during lookup.',
    scanning: 'Scanning…',
  },
  buy: {
    selectTicket: 'Select ticket',
    selectJumpTime: 'Choose jump time',
    sectionEntry: 'Entry',
    sectionFamily: 'Family',
    sectionCombo: weekdayComboCopy.en.name,
    comboPeople: '2 people',
    comboDuration: '60 min',
    comboPizza: '1 pizza',
    comboSeason: weekdayComboCopy.en.availability,
    comboPackageNote: '2 people',
    entry60: '60 min entry',
    entry90: '90 min entry',
    entry120: '120 min entry',
    family60: '60 min family',
    family90: '90 min family',
    family120: '120 min family',
    perPersonNote: 'Per person',
    familyNote: '4 jumpers, 1 adult 18+',
    howMany: 'How many?',
    quantityJumpers: 'Number of jumpers',
    quantityPackages: 'Number of family packages',
    quantityComboPackages: 'Number of combo packages',
    total: 'Total',
    toPay: 'To pay',
    selectTime: 'Choose start time',
    selectTimeToday: 'Today',
    selectTimeDesc: 'Choose when you want to start jumping.',
    startTimeLabel: 'Start time',
    todaySuffix: 'today',
    loadingAvailabilityTitle: 'Loading available spots',
    loadingAvailabilityDesc: 'Checking capacity for',
    loadingAvailabilityGeneric: 'Checking capacity in Roller.',
    spotsLeft: 'spots left',
    spotsFull: 'Fully booked',
    maxReached: 'Max',
    contactTitle: 'Your contact',
    contactDesc: 'We send confirmation and reminders.',
    emailLabel: 'Email',
    emailPlaceholder: 'guest@example.com',
    creating: 'Creating booking…',
    confirmCreate: 'Confirm & continue',
    skipContact: 'Skip',
    availabilityFailed: 'We could not load available times.',
    retryAvailability: 'Try again',
    noProductsAvailableTitle: 'No products available',
    noProductsAvailableDesc: 'There are no bookable products for the selected time.',
    chooseAnotherTime: 'Choose another time',
    spotsAvailable: 'Available',
    firstNameLabel: 'First name',
    lastNameLabel: 'Last name',
    phoneLabel: 'Phone',
    phonePlaceholder: '0700000000',
    quoting: 'Calculating price…',
    quoteFailed: 'We could not calculate the price.',
    draftFailed: 'We could not reserve the booking.',
    unavailableProductFallback: 'The product',
    unavailableProductPrefix: 'is not available at',
    unavailableProductAction: 'Go back to add-ons and remove it or choose another time.',
    reviewTitle: 'Summary',
    reviewDesc: 'Your entry, add-ons, and total before payment.',
    jumpTimeLabel: 'Jump time',
    jumpersLabel: 'Jumpers',
    createDraft: 'Go to payment',
    pendingTitle: 'Payment pending',
    pendingDesc: 'The booking is reserved in Playground. Payment is connected when Roller payment access is approved.',
    draftStatus: 'Status',
    paymentPending: 'Waiting for payment',
    paymentTitle: 'Pay',
    paymentSetupTitle: 'Preparing payment',
    paymentMethodTitle: 'Payment',
    paymentStarting: 'Starting payment',
    paymentReadyDesc: 'Payment is loading for',
    paymentReceived: 'Payment received',
    paymentReceivedDesc: 'We are waiting for payment confirmation.',
    paymentApprovedTitle: 'Payment complete',
    paymentApprovedDesc: 'We are syncing the booking. Roller sends the confirmation and receipt to the booking email.',
    paymentFailedTitle: 'Payment stopped',
    paymentFailedDesc: 'The payment could not be completed. Your choices are saved and you can choose another payment method.',
    paymentRecoveryTitle: 'We cannot confirm the payment yet',
    paymentRecoveryDescription: 'Do not pay again for the same purchase. Check the status again in a moment. If the problem continues, we will help you check the purchase when you arrive at JumpYard.',
    paymentRetryMethod: 'Choose another payment method',
    paymentCheckStatus: 'Check payment status',
    paymentChecking: 'Checking your payment',
    paymentBlockedTitle: 'Payment unavailable',
    paymentBlockedDesc: 'The payment package could not start for this booking.',
    paymentMissingJwt: 'The booking is missing the Roller payment token.',
    paymentMissingConfig: 'The booking is missing Roller payment configuration.',
    paymentUnknownResult: 'The payment was received but is not finally confirmed.',
    paymentSyncing: 'Payment complete',
    paymentSyncLoader: 'Loading booking...',
    paymentSyncFailed: 'Payment is complete but the booking has not synced yet.',
    paymentSyncFallback: 'Check again in a moment. If the problem continues, we will help you check the purchase when you arrive at JumpYard.',
    paymentRetrySync: 'Load booking again',
    giftCardLabel: 'Gift card',
    giftCardPlaceholder: 'Enter gift card number',
    giftCardHelp: 'Optional. Roller checks the gift card before the booking is reserved.',
    giftCardApplied: 'Applied',
    giftCardRejected: 'Rejected',
    giftCardErrorFallback: 'The gift card could not be used.',
    giftCardFixHint: 'Check the number or remove the gift card to continue.',
    clipCardLabel: 'Clip card',
    clipCardPlaceholder: 'Enter clip-card code',
    clipCardHelp: 'Optional. Works for clip cards such as 10-, 20-, or 30-visit cards. Roller checks which entry products the code covers.',
    clipCardApplied: 'Applied',
    clipCardRejected: 'Rejected',
    clipCardErrorFallback: 'The clip-card code could not be used.',
    clipCardFixHint: 'Check the code or remove it to continue.',
    paymentOptionsTitle: 'Add gift card or clip-card code',
    paymentOptionsApplyGiftCard: 'Apply gift card',
    paymentOptionsApplyClipCard: 'Apply clip card',
    paymentOptionsApplyBoth: 'Apply gift card and clip card',
    paymentOptionsApplyChanges: 'Apply change',
    paymentOptionsUpdateRequired: 'Apply the gift card or clip card before going to payment.',
    paymentCodeReady: 'Ready to apply',
    paymentCodeDone: 'Ready',
    paymentCodeMaxLength: 'Max 32 characters',
    originalTotal: 'Original total',
    noPaymentTitle: 'Booking ready',
    noPaymentDesc: 'The gift card or clip card covers the full amount. We are loading the booking and continuing check-in.',
    noPaymentStatus: 'No card payment needed',
  },
  buyRecovery: {
    title: 'We found your latest check-in.',
    description: 'Continue where you left off.',
    checking: 'Loading booking',
    failedTitle: 'We found your latest check-in.',
    failedDescription: 'The booking is saved here, but we could not load it right now. Try again or start over.',
    completedUnavailableTitle: 'We cannot show your previous booking',
    completedUnavailableDescription: 'You had already completed the booking, but we cannot load it right now. Try again to view it, or make a new booking.',
    unsafeDescription: 'We found a saved check-in, but it is missing a booking number. Start over to create a new safe path.',
    retry: 'Try again',
    startOver: 'Start over',
  },
  booking: {
    ref: 'Booking',
    today: 'Today',
    date: 'Date',
    time: 'Time',
    duration: 'Duration',
    guest: 'Guest',
    jumpers: 'Jumpers',
    tickets: 'Tickets',
    addons: 'Add-ons',
    none: 'None',
    paidInFull: 'Paid',
    notPaid: 'Unpaid',
    title: 'Your booking',
    subtitle: "Looks right? Let's go.",
    product: 'Product',
    cta: 'Yes, start check-in',
    startingSession: 'Starting check-in…',
    paymentRequiredCta: 'Payment required',
    paymentRequiredHint: 'Payment is built in an upcoming ticket. Please call staff for now.',
    partiallyPaid: 'Partially paid',
    checkInAtRegisterCta: 'Check in at the register',
    checkInAtRegisterHint: 'This booking needs to be checked in at the register.',
    sessionStartFailed: 'We could not start check-in. Try again or call staff.',
    sessionPaymentRequired: 'This booking still has payment due. Please call staff so we can help you continue.',
    sessionWrongDate: 'This booking is for another date. Please call staff so we can check it.',
    sessionAlreadyRedeemed: 'These tickets already look used. Please call staff so we can check the booking.',
    sessionNotFresh: 'We need to update this booking before check-in. Please call staff for now.',
    timeHint: 'Takes about 1–2 min. Next: safety video.',
  },
  safetyVideo: {
    title: 'Safety video',
    description: 'Watch the video together with everyone who will jump.',
    buyTitle: 'Safety walkthrough',
    buyDescription: 'Watch the video together with everyone who will jump.',
    play: 'Play',
    playing: 'Video playing…',
    watchFull: 'Watch the full video',
    done: 'Confirm safety rules',
    buyDone: 'Confirm safety rules',
    replay: 'Watch again',
    durationBadge: 'about 15 sec',
  },
  safetyAttest: {
    title: 'Safety rules',
    description: 'Confirm each rule before continuing.',
    buyTitle: 'Ready for entry',
    buyDescription: 'Confirm the safety rules so staff can check you in.',
    ageRulesTitle: 'Age rules',
    ageRules: {
      adultInArea35: 'Ages 3–5: an adult must accompany the child inside the activity area.',
      adultInVenue610: 'Ages 6–10: may jump alone if a responsible adult is on the premises.',
      canJumpAlone11: 'Ages 11 and up: may jump alone.',
    },
    safetyRulesTitle: 'Safety rules',
    rules: {
      onePerTrampoline: 'Only one person per trampoline – risk of collisions and uncontrollable bounces.',
      avoidEdgePadding: 'Avoid the edge padding – risk of spraining your ankle.',
      landOnBackOrBottom: 'Always land on your bottom or back in foam pits and airbags. Other landings can cause serious injury.',
      tricksWithinAbility: 'Only attempt tricks and flips you can safely perform.',
      noRunning: 'Do not run in the park – risk of collisions and falls.',
    },
    finalAttest: 'I confirm that everyone in my booking has read and understood the rules.',
    cta: 'I understand, continue',
    readyForStaffProcessing: 'Getting staff handoff ready...',
    readyForStaffFailed: 'We could not make this check-in ready for staff. Try again or call staff.',
    paymentConfirmationWaiting: 'Your payment is complete. We are waiting for the booking system to confirm the booking, which can take up to a minute or so.',
    paymentConfirmationDelayed: 'The booking is not confirmed yet. Do not pay again. Check again in a moment. If the problem continues, we will help you when you arrive at JumpYard.',
    paymentConfirmationRetry: 'Check again',
  },
  addons: {
    title: 'Add-ons',
    choices: {
      preview: 'Preview · sample prices · no real purchases',
      socksTitle: 'Approved grip socks',
      socksBenefit: 'Great grip. Required for every jumper.',
      ownSocks: 'We brought approved grip socks',
      socksRequired: 'Add grip socks or confirm that you brought approved grip socks.',
      bottleTitle: 'Water bottle',
      bottleEnvironment: 'No disposable cups, to reduce waste.',
      ownBottle: 'We brought our own water bottle',
      bottleRequired: 'Add a water bottle or confirm that you brought your own.',
      lockBenefit: 'Lock away your things while you jump.',
      coffeeBenefit: 'A tasty break between jumps.',
      skyRiderBenefit: 'See the park from above on our high ropes course.',
      recommended: 'Recommended',
      included: '{count} already included',
      quantity: 'Quantity to add',
      perPair: 'per pair',
      add: 'Add',
      remove: 'Remove',
      unavailableRequired: 'Not available to buy here right now. If you did not bring your own, ask our staff.',
    },
    description: "Pick extras, skip anything you don't want.",
    loading: 'Loading add-ons',
    socksSectionTitle: 'Approved jump socks',
    socksHelp: 'Everyone who jumps needs approved jump socks.',
    socksAlreadyHave: 'We already have approved jump socks.',
    socksAddPrompt: 'Add the socks you need.',
    socksRecommendedCount: 'Recommended count',
    socksSelectedCount: 'Selected',
    waterBottleSectionTitle: 'Water bottle',
    waterBottleHelp: 'Do you have your own water bottle? Sorry, we cannot hand out disposable cups for environmental reasons.',
    waterBottleAlreadyHave: 'We brought our own water bottle.',
    alreadyInBooking: 'Already included',
    total: 'Add-ons total',
    perJumper: 'per jumper',
    each: 'each',
    eachLong: 'each',
    perPerson: 'per person',
    connectedValueProp: 'Most chosen add-on',
    unsupported: 'Coming later',
    unsupportedSelection: 'This add-on cannot be created automatically yet.',
    contactTitle: 'Add-on contact',
    contactDesc: 'Roller requires contact details for the separate add-on booking.',
    quoteFailed: 'We could not calculate the add-on.',
    draftFailed: 'We could not reserve the add-on.',
    reviewTitle: 'Review add-on',
    reviewDesc: 'The price comes directly from the booking system.',
    createDraft: 'Go to payment',
    paymentTitle: 'Pay add-on',
    paymentApprovedTitle: 'Payment complete',
    paymentApprovedDesc: 'The add-on is paid. Roller sends the confirmation and receipt to the booking email.',
    pendingTitle: 'Payment pending',
    pendingDesc: 'The add-on is reserved as a separate Playground booking. Payment is connected when Roller payment access is approved.',
    products: {
      skyriderLabel: 'SkyRider',
      skyriderDesc: 'Zip-line experience. Requires min 100 cm.',
      connectedLabel: 'Connected',
      connectedDesc: 'Track jumps, leaderboards, highlight reel.',
      coffeeLabel: 'Filter coffee',
      coffeeDesc: 'Coffee for the grown-ups while the kids jump.',
      extraPersonLabel: 'Extra person',
      extraPersonDesc: 'Add another jumper to this booking.',
      lockLabel: 'Padlock',
      lockDesc: 'Padlock for the lockers.',
      socksLabel: 'Socks',
      socksDesc: 'Jump socks, required.',
      waterBottleLabel: 'Water bottle',
      waterBottleDesc: 'Add a bottle or confirm you brought your own.',
    },
  },
  skyrider: {
    title: 'Before SkyRider',
    description: 'Check the height requirement and when SkyRider fits best.',
    infoLabel: 'SkyRider information',
    requirementTitle: 'Minimum 100 cm',
    requirementText: 'Everyone riding SkyRider needs to be at least 100 cm tall.',
    timingTitle: 'Best after jump time',
    timingText: 'We recommend doing SkyRider after the jump session.',
    confirmCheckbox: 'I confirm that all SkyRider riders are at least 100 cm.',
    removeSkyRider: 'Remove SkyRider',
  },
  connected: {
    title: 'Connected profiles',
    description: 'Each Connected band is linked to a profile. Enter names so staff know who gets which band.',
    profile: 'Profile',
    namePlaceholder: 'Name',
    avatar: 'Icon',
    confirm: 'Confirm profiles',
  },
  payment: {
    title: 'Payment',
    description: 'Tap your card on the terminal when ready.',
    booking: 'Booking',
    items: "What you're paying for",
    total: 'Total',
    pay: 'Pay',
    afterPaymentHint: 'After payment you continue to the entrance.',
    baseProduct: 'Booking',
    addonsLabel: 'Add-ons',
  },
  confirm: {
    title: 'Ready for entry',
    subtitle: 'Pick up wristbands from staff.',
    onsiteSubtitle: 'Pick up wristbands from staff.',
    smsSubtitle: 'Go to staff when you arrive at the park.',
    kioskSubtitle: 'Take the printout and show it when you pick up wristbands.',
    pickupCode: 'Booking',
    handoffTitle: 'Show at entry',
    handoffCode: 'Handoff code',
    qrHelp: 'Show the QR code to staff. Name, phone, or email also works.',
    entryTicketFallback: 'Entry',
    staffHandout: 'To pick up',
    otherAddons: 'Also on your booking',
    wristbands: 'Wristbands',
    connectedBands: 'Connected bands',
    complete: 'Done & next guest',
    done: 'Make a new booking',
    showStaffNote: 'Show staff',
    alreadyCheckedInTitle: 'Already checked in',
    alreadyCheckedInSubtitle: 'This booking has already been completed.',
    alreadyCheckedInHelp: 'Call staff if anything looks wrong.',
  },
  print: {
    title: 'Done, head to the park!',
    subtitle: 'Your receipt is printing.',
    printing: 'Printing…',
  },
  present: {
    eyebrow: 'Show at entrance',
    title: 'Ready for the park',
    instruction: 'Go to staff to get your wristbands.',
    startOver: 'Start over',
  },
  extend: {
    loading: 'Loading extension…',
    view: {
      title: 'Extend your session',
      subtitle: '+30 minutes of extra jump time.',
      currentEnd: 'Current end',
      newEnd: 'New end',
      price: 'Price',
      cta: 'Pay',
    },
    pay: {
      title: 'Extension payment',
      subtitle: '+30 min for',
      swish: 'Swish',
      card: 'Card',
    },
    qr: {
      eyebrow: 'Band swap',
      title: '+30 minutes confirmed',
      newEndPrefix: 'New end:',
      nextStepLabel: 'Next step',
      nextStepText: 'Go to the cashier or staff to get a new wristband with the updated end time.',
    },
    error: {
      title: "We couldn't load the extension",
      expired: 'This link has expired. Please call staff.',
      already: 'This booking has already been extended.',
      generic: 'Something went wrong. Please call staff.',
    },
  },
};

export type Translations = typeof sv;
const translations: Record<Language, Translations> = { sv, en };

interface LanguageContextValue {
  lang: Language;
  t: Translations;
  toggleLang: () => void;
  setLang: (l: Language) => void;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'sv',
  t: sv,
  toggleLang: () => {},
  setLang: () => {},
});

const STORAGE_KEY = 'jy.lang';

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'sv';
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY) as Language | null;
      return stored === 'sv' || stored === 'en' ? stored : 'sv';
    } catch {}
    return 'sv';
  });

  const setLang = (l: Language) => {
    setLangState(l);
    try {
      localStorage.setItem(STORAGE_KEY, l);
    } catch {}
  };
  const toggleLang = () => setLang(lang === 'sv' ? 'en' : 'sv');

  // #350: the document language follows the guest's choice for assistive technology.
  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggleLang, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  return useContext(LanguageContext);
}
