'use client';
import { createContext, useContext, useState } from 'react';

type Language = 'sv' | 'en';

const sv = {
  common: {
    back: 'Tillbaka',
    continue: 'Fortsätt',
    confirm: 'Bekräfta',
    cancel: 'Avbryt',
    skip: 'Hoppa över',
    processing: 'Behandlar…',
    loading: 'Laddar…',
    currency: 'kr',
    done: 'Klart',
    yes: 'Ja',
    no: 'Nej',
    callStaff: 'Hämta personal',
    staffCalled: 'Personal är på väg',
    stillThere: 'Är du kvar?',
    stillThereDesc: 'Tryck var som helst för att fortsätta, annars börjar vi om.',
    imHere: 'Jag är kvar',
  },
  progress: {
    booking: 'Bokning',
    safety: 'Säkerhet',
    extras: 'Tillägg',
    payment: 'Betalning',
    done: 'Klar',
  },
  buyProgress: {
    entry: 'Entré',
    addons: 'Tillägg',
    payment: 'Betalning',
    safety: 'Säkerhet',
    done: 'Klar',
  },
  idle: {
    tap: 'Tryck för att börja',
    line1: 'Välkommen till',
    line2: 'JumpYard',
  },
  start: {
    eyebrowKiosk: 'Kiosk',
    eyebrowPark: 'Park-QR',
    eyebrowSms: 'SMS-länk',
    title: 'Välkommen!',
    subtitle: 'Samma incheckning oavsett hur du kom hit.',
    cta: 'Starta',
  },
  choice: {
    title: 'Vad vill du göra?',
    haveBooking: 'Jag har en bokning',
    haveBookingDesc: 'Hitta din bokning med bokningskod',
    buyTickets: 'Köp entré',
    buyTicketsDesc: 'Köp entré och fortsätt till check-in',
  },
  lookup: {
    title: 'Hitta din bokning',
    description: 'Skanna QR-koden eller skriv in din bokningsnummer.',
    placeholder: 'Bokningsnummer',
    cta: 'Sök',
    notFound: 'Vi hittade ingen bokning med det numret.',
    tryAgain: 'Kontrollera numret eller hämta personal.',
    paymentRequired: 'Bokningen har kvar att betala.',
    paymentRequiredDesc: 'Hämta personal så hjälper vi dig vidare.',
    wrongDate: 'Bokningen gäller ett annat datum.',
    wrongDateDesc: 'Kontrollera datumet eller hämta personal.',
    noRedeemableTickets: 'Bokningen saknar biljetter att checka in.',
    noRedeemableTicketsDesc: 'Hämta personal så kontrollerar vi bokningen.',
    serviceUnavailable: 'Vi kunde inte nå bokningssystemet.',
    serviceUnavailableDesc: 'Försök igen eller hämta personal.',
    lookupFailed: 'Något gick fel vid sökningen.',
    scanning: 'Skannar…',
  },
  buy: {
    selectTicket: 'Välj biljett',
    selectJumpTime: 'Välj hopptid',
    sectionEntry: 'Entré',
    sectionFamily: 'Familj',
    entry60: '60 min entré',
    entry90: '90 min entré',
    entry120: '120 min entré',
    family60: '60 min familj',
    family90: '90 min familj',
    family120: '120 min familj',
    familyNote: '4 hoppare per paket',
    howMany: 'Hur många?',
    quantityJumpers: 'Antal hoppare',
    quantityPackages: 'Antal familjepaket',
    total: 'Totalt',
    toPay: 'Att betala',
    selectTime: 'Välj starttid',
    selectTimeToday: 'Idag',
    selectTimeDesc: 'Välj när ni vill börja hoppa.',
    startTimeLabel: 'Starttid',
    todaySuffix: 'idag',
    loadingAvailabilityTitle: 'Hämtar tillgängliga platser',
    loadingAvailabilityDesc: 'Vi kontrollerar kapacitet för',
    loadingAvailabilityGeneric: 'Vi kontrollerar kapacitet i Roller.',
    spotsLeft: 'platser kvar',
    spotsFull: 'Fullbokat',
    maxReached: 'Max',
    contactTitle: 'Din kontakt',
    contactDesc: 'Vi skickar bekräftelse och påminnelser.',
    emailLabel: 'E-post',
    emailPlaceholder: 'gäst@exempel.se',
    creating: 'Skapar bokning…',
    confirmCreate: 'Bekräfta & fortsätt',
    skipContact: 'Hoppa över',
    availabilityFailed: 'Vi kunde inte hämta lediga tider.',
    retryAvailability: 'Försök igen',
    spotsAvailable: 'Ledigt',
    firstNameLabel: 'Förnamn',
    lastNameLabel: 'Efternamn',
    phoneLabel: 'Telefon',
    phonePlaceholder: '0700000000',
    quoting: 'Räknar pris…',
    quoteFailed: 'Vi kunde inte räkna ut priset.',
    draftFailed: 'Vi kunde inte reservera bokningen.',
    unavailableProductFallback: 'Produkten',
    unavailableProductPrefix: 'är inte tillgänglig kl.',
    unavailableProductAction: 'Gå tillbaka till tillägg och ta bort valet eller välj en annan tid.',
    reviewTitle: 'Sammanställning',
    reviewDesc: 'Här är din entré, dina tillägg och totalen innan betalning.',
    jumpTimeLabel: 'Hopptid',
    jumpersLabel: 'Antal hoppare',
    createDraft: 'Gå till betalning',
    pendingTitle: 'Betalning väntar',
    pendingDesc: 'Bokningen är reserverad i Playground. Betalningssteget kopplas in när Roller-betalningen är godkänd.',
    draftStatus: 'Status',
    paymentPending: 'Väntar på betalning',
    paymentTitle: 'Betala',
    paymentSetupTitle: 'Förbereder betalning',
    paymentMethodTitle: 'Betalning',
    paymentStarting: 'Startar betalning',
    paymentReadyDesc: 'Betalningen laddas för',
    paymentReceived: 'Betalning mottagen',
    paymentReceivedDesc: 'Vi väntar på bekräftelse från betalningen.',
    paymentApprovedTitle: 'Betalning klar',
    paymentApprovedDesc: 'Vi hämtar bokningen och fortsätter check-in.',
    paymentFailedTitle: 'Betalningen stoppades',
    paymentFailedDesc: 'Betalningen kunde inte slutföras. Försök igen eller hämta personal.',
    paymentBlockedTitle: 'Betalning saknas',
    paymentBlockedDesc: 'Betalningspaketet kunde inte startas för den här bokningen.',
    paymentMissingJwt: 'Bokningen saknar betalningstoken från Roller.',
    paymentMissingConfig: 'Bokningen saknar betalningskonfiguration från Roller.',
    paymentUnknownResult: 'Betalningen är mottagen men inte slutligt bekräftad.',
    paymentSyncing: 'Hämtar bokningen...',
    paymentSyncFailed: 'Betalningen verkar klar men bokningen har inte hunnit synkas. Försök igen om några sekunder.',
    paymentRetrySync: 'Hämta bokningen igen',
    giftCardLabel: 'Presentkort',
    giftCardPlaceholder: 'Ange presentkortsnummer',
    giftCardHelp: 'Valfritt. Presentkortet kontrolleras av Roller innan bokningen reserveras.',
    giftCardApplied: 'Applicerat',
    giftCardRejected: 'Ej godkänt',
    giftCardErrorFallback: 'Presentkortet kunde inte användas.',
    giftCardFixHint: 'Kontrollera numret eller ta bort presentkortet för att fortsätta.',
    clipCardLabel: 'Klippkort',
    clipCardPlaceholder: 'Ange klippkortskod',
    clipCardHelp: 'Valfritt. Gäller klippkort som 10-, 20- eller 30-kort. Roller kontrollerar vilka entréprodukter koden täcker.',
    clipCardApplied: 'Applicerat',
    clipCardRejected: 'Ej godkänt',
    clipCardErrorFallback: 'Klippkortskoden kunde inte användas.',
    clipCardFixHint: 'Kontrollera koden eller ta bort den för att fortsätta.',
    paymentOptionsTitle: 'Lägg till presentkort eller klippkort',
    paymentOptionsApplyGiftCard: 'Applicera presentkort',
    paymentOptionsApplyClipCard: 'Applicera klippkort',
    paymentOptionsApplyBoth: 'Applicera presentkort och klippkort',
    paymentOptionsApplyChanges: 'Applicera ändring',
    paymentOptionsUpdateRequired: 'Applicera presentkortet eller klippkortet innan du går till betalning.',
    paymentCodeReady: 'Redo att applicera',
    paymentCodeDone: 'Klart',
    paymentCodeMaxLength: 'Max 32 tecken',
    originalTotal: 'Ordinarie total',
    noPaymentTitle: 'Bokning klar',
    noPaymentDesc: 'Presentkortet eller klippkortet täcker hela beloppet. Vi hämtar bokningen och fortsätter check-in.',
    noPaymentStatus: 'Ingen kortbetalning behövs',
  },
  booking: {
    ref: 'Bokning',
    today: 'Idag',
    date: 'Datum',
    time: 'Tid',
    duration: 'Längd',
    guest: 'Gäst',
    jumpers: 'Hoppare',
    addons: 'Tillägg',
    none: 'Inga',
    paidInFull: 'Betald',
    notPaid: 'Obetald',
    title: 'Din bokning',
    subtitle: 'Ser det rätt ut? Då kör vi.',
    product: 'Produkt',
    cta: 'Ja, starta incheckning',
    startingSession: 'Startar incheckning…',
    paymentRequiredCta: 'Betalning krävs',
    paymentRequiredHint: 'Betalning byggs i en kommande ticket. Hämta personal tills vidare.',
    sessionStartFailed: 'Vi kunde inte starta incheckningen. Försök igen eller hämta personal.',
    sessionPaymentRequired: 'Bokningen har kvar att betala. Hämta personal så hjälper vi dig vidare.',
    sessionWrongDate: 'Bokningen gäller ett annat datum. Hämta personal så kontrollerar vi bokningen.',
    sessionAlreadyRedeemed: 'Biljetterna verkar redan vara använda. Hämta personal så kontrollerar vi bokningen.',
    sessionNotFresh: 'Vi behöver uppdatera bokningen innan incheckning. Hämta personal tills vidare.',
    timeHint: 'Tar ca 1–2 min. Nästa steg: säkerhetsvideo.',
  },
  safetyVideo: {
    title: 'Säkerhetsvideo',
    description: 'Titta på videon innan du kan gå vidare.',
    play: 'Spela upp',
    playing: 'Videon spelas…',
    watchFull: 'Titta hela videon',
    done: 'Klart, fortsätt',
  },
  safetyAttest: {
    title: 'Säkerhetsregler',
    description: 'Bekräfta varje regel innan du fortsätter.',
    ageRulesTitle: 'Åldersregler',
    ageRules: {
      adultInArea35: '3–5 år: vuxen måste medfölja i aktivitetsområdet.',
      adultInVenue610: '6–10 år: får hoppa själv om ansvarig vuxen finns i lokalen.',
      canJumpAlone11: '11 år och uppåt: får hoppa själv.',
    },
    safetyRulesTitle: 'Säkerhetsregler',
    rules: {
      onePerTrampoline: 'Endast en person per trampolin – risk för krock och okontrollerbar studs.',
      avoidEdgePadding: 'Undvik kantskydden – risk att stuka foten.',
      landOnBackOrBottom: 'Landa alltid på rumpa eller rygg i foampit och airbag. Andra landningar kan leda till allvarliga skador.',
      tricksWithinAbility: 'Gör bara tricks och volter som du klarar av.',
      noRunning: 'Spring inte i parken – risk för krock och fall.',
    },
    finalAttest: 'Jag intygar att samtliga i min bokning har tagit del av reglerna och förstått dem.',
    cta: 'Jag förstår, fortsätt',
    readyForStaffProcessing: 'G\u00f6r redo f\u00f6r personal...',
    readyForStaffFailed: 'Vi kunde inte g\u00f6ra incheckningen redo f\u00f6r personal. F\u00f6rs\u00f6k igen eller h\u00e4mta personal.',
  },
  addons: {
    title: 'Tillägg',
    description: 'Välj till extra, hoppa över det du inte vill ha.',
    alreadyInBooking: 'Ingår redan',
    total: 'Tillägg totalt',
    perJumper: 'per hoppare',
    each: 'st',
    perPerson: 'per person',
    connectedValueProp: 'Mest valt tillägg',
    scrollHint: 'tillägg att välja mellan — scrolla ner',
    unsupported: 'Kommer senare',
    unsupportedSelection: 'Det tillägget kan inte skapas automatiskt ännu.',
    contactTitle: 'Kontakt för tillägget',
    contactDesc: 'Roller kräver kontaktuppgifter för den separata tilläggsbokningen.',
    quoteFailed: 'Vi kunde inte räkna ut tillägget.',
    draftFailed: 'Vi kunde inte reservera tillägget.',
    reviewTitle: 'Kontrollera tillägg',
    reviewDesc: 'Priset hämtas direkt från bokningssystemet.',
    createDraft: 'Gå till betalning',
    paymentTitle: 'Betala tillägg',
    paymentApprovedTitle: 'Betalning klar',
    paymentApprovedDesc: 'Tillägget är betalt. Vi fortsätter check-in.',
    pendingTitle: 'Betalning väntar',
    pendingDesc: 'Tillägget är reserverat som en separat Playground-bokning. Betalningssteget kopplas in när Roller-betalningen är godkänd.',
    products: {
      skyriderLabel: 'SkyRider',
      skyriderDesc: 'Linbane-upplevelsen. Kräver min 100 cm.',
      connectedLabel: 'Connected',
      connectedDesc: 'Spåra hopp, tävla på topplistor, få highlight-klipp.',
      coffeeLabel: 'Kaffe',
      coffeeDesc: 'Kaffe åt de vuxna medan barnen hoppar.',
      extraPersonLabel: 'Extra person',
      extraPersonDesc: 'Lägg till en till hoppare.',
      lockLabel: 'Hänglås',
      lockDesc: 'Hänglås till skåpen.',
      socksLabel: 'Strumpor',
      socksDesc: 'Hoppstrumpor, obligatoriska.',
    },
  },
  skyrider: {
    title: 'Innan SkyRider',
    description: 'Kontrollera att varje SkyRider-pass används av en gäst som uppfyller kraven.',
    infoLabel: 'SkyRider-information',
    requirementTitle: 'Minst 100 cm',
    requirementText: 'Gästen måste vara minst 100 cm lång för att åka.',
    safetyTitle: 'Säkerhetscheck',
    safetyText: 'Personal gör en sista säkerhetskontroll innan åket.',
    timingTitle: 'Åk efter hopptiden',
    timingText: 'Vi rekommenderar SkyRider efter trampolintiden, så hopptiden inte avbryts.',
    confirmCheckbox: 'Jag bekräftar att SkyRider-passen endast används av personer som är minst 100 cm långa och följer personalens säkerhetscheck.',
    removeSkyRider: 'Ta bort SkyRider',
  },
  connected: {
    title: 'Connected-profiler',
    description: 'Varje Connected-band kopplas till en profil. Skriv namn så personalen vet vem som får vilket band.',
    profile: 'Profil',
    namePlaceholder: 'Namn',
    avatar: 'Ikon',
    confirm: 'Bekräfta profiler',
  },
  payment: {
    title: 'Betalning',
    description: 'Håll kortet mot terminalen när du är redo.',
    booking: 'Bokning',
    items: 'Vad du betalar för',
    total: 'Totalt',
    pay: 'Betala',
    afterPaymentHint: 'Efter betalning får du en kod att visa vid entrén.',
    baseProduct: 'Bokning',
    addonsLabel: 'Tillägg',
  },
  confirm: {
    title: 'Redo f\u00f6r personal',
    subtitle: 'Visa koden nedan vid entr\u00e9n. Personalen slutf\u00f6r incheckningen.',
    pickupCode: 'Personalkod',
    staffHandout: 'Att hämta ut hos personalen',
    otherAddons: 'Övriga tillägg i bokningen',
    wristbands: 'Armband',
    connectedBands: 'Connected-band',
    complete: 'Klart & nästa gäst',
    done: 'Börja om',
    showStaffNote: 'Visa personalen',
    alreadyCheckedInTitle: 'Redan incheckad',
    alreadyCheckedInSubtitle: 'Den här bokningen är redan slutförd.',
    alreadyCheckedInHelp: 'Hämta personal om något inte stämmer.',
  },
  print: {
    title: 'Klart, gå till banan!',
    subtitle: 'Ditt kvitto skrivs ut.',
    printing: 'Skriver ut…',
  },
  present: {
    eyebrow: 'Visa vid entrén',
    title: 'Redo för parken',
    instruction: 'Visa QR-koden eller personalkoden till personalen för att få armband.',
    startOver: 'Börja om',
  },
  extend: {
    loading: 'Laddar förlängning…',
    view: {
      title: 'Förläng din session',
      subtitle: '+30 minuter extra hopptid.',
      currentEnd: 'Nuvarande sluttid',
      newEnd: 'Ny sluttid',
      price: 'Pris',
      cta: 'Betala',
    },
    pay: {
      title: 'Betala förlängning',
      subtitle: '+30 min för',
      swish: 'Swish',
      card: 'Kort',
    },
    qr: {
      eyebrow: 'Bandbyte',
      title: '+30 minuter bekräftat',
      newEndPrefix: 'Ny sluttid:',
      nextStepLabel: 'Nästa steg',
      nextStepText: 'Gå till kassan eller personalen för att få ett nytt band med uppdaterad sluttid.',
    },
    error: {
      title: 'Vi kunde inte ladda förlängningen',
      expired: 'Länken har gått ut. Hämta personal.',
      already: 'Den här bokningen är redan förlängd.',
      generic: 'Något gick fel. Hämta personal.',
    },
  },
};

const en: typeof sv = {
  common: {
    back: 'Back',
    continue: 'Continue',
    confirm: 'Confirm',
    cancel: 'Cancel',
    skip: 'Skip',
    processing: 'Processing…',
    loading: 'Loading…',
    currency: 'kr',
    done: 'Done',
    yes: 'Yes',
    no: 'No',
    callStaff: 'Call staff',
    staffCalled: 'Staff is on the way',
    stillThere: 'Are you still there?',
    stillThereDesc: 'Tap anywhere to continue, otherwise we restart.',
    imHere: "I'm here",
  },
  progress: {
    booking: 'Booking',
    safety: 'Safety',
    extras: 'Extras',
    payment: 'Payment',
    done: 'Done',
  },
  buyProgress: {
    entry: 'Entry',
    addons: 'Add-ons',
    payment: 'Payment',
    safety: 'Safety',
    done: 'Done',
  },
  idle: {
    tap: 'Tap to start',
    line1: 'Welcome to',
    line2: 'JumpYard',
  },
  start: {
    eyebrowKiosk: 'Kiosk',
    eyebrowPark: 'Park QR',
    eyebrowSms: 'SMS Link',
    title: 'Welcome!',
    subtitle: 'Same check-in whichever way you arrived.',
    cta: 'Start',
  },
  choice: {
    title: 'What would you like to do?',
    haveBooking: 'I have a booking',
    haveBookingDesc: 'Find your booking with booking code',
    buyTickets: 'Buy entry',
    buyTicketsDesc: 'Buy entry and continue to check-in',
  },
  lookup: {
    title: 'Find your booking',
    description: 'Scan the QR code or enter your booking number.',
    placeholder: 'Booking number',
    cta: 'Search',
    notFound: "We couldn't find a booking with that number.",
    tryAgain: 'Check the number or call staff.',
    paymentRequired: 'This booking still has payment due.',
    paymentRequiredDesc: 'Please call staff so we can help you continue.',
    wrongDate: 'This booking is for another date.',
    wrongDateDesc: 'Check the date or call staff.',
    noRedeemableTickets: 'This booking has no tickets to check in.',
    noRedeemableTicketsDesc: 'Please call staff so we can check the booking.',
    serviceUnavailable: "We couldn't reach the booking system.",
    serviceUnavailableDesc: 'Try again or call staff.',
    lookupFailed: 'Something went wrong during lookup.',
    scanning: 'Scanning…',
  },
  buy: {
    selectTicket: 'Select ticket',
    selectJumpTime: 'Choose jump time',
    sectionEntry: 'Entry',
    sectionFamily: 'Family',
    entry60: '60 min entry',
    entry90: '90 min entry',
    entry120: '120 min entry',
    family60: '60 min family',
    family90: '90 min family',
    family120: '120 min family',
    familyNote: '4 jumpers per package',
    howMany: 'How many?',
    quantityJumpers: 'Number of jumpers',
    quantityPackages: 'Number of family packages',
    total: 'Total',
    toPay: 'To pay',
    selectTime: 'Choose start time',
    selectTimeToday: 'Today',
    selectTimeDesc: 'Choose when you want to start jumping.',
    startTimeLabel: 'Start time',
    todaySuffix: 'today',
    loadingAvailabilityTitle: 'Loading available spots',
    loadingAvailabilityDesc: 'Checking capacity for',
    loadingAvailabilityGeneric: 'Checking capacity in Roller.',
    spotsLeft: 'spots left',
    spotsFull: 'Fully booked',
    maxReached: 'Max',
    contactTitle: 'Your contact',
    contactDesc: 'We send confirmation and reminders.',
    emailLabel: 'Email',
    emailPlaceholder: 'guest@example.com',
    creating: 'Creating booking…',
    confirmCreate: 'Confirm & continue',
    skipContact: 'Skip',
    availabilityFailed: 'We could not load available times.',
    retryAvailability: 'Try again',
    spotsAvailable: 'Available',
    firstNameLabel: 'First name',
    lastNameLabel: 'Last name',
    phoneLabel: 'Phone',
    phonePlaceholder: '0700000000',
    quoting: 'Calculating price…',
    quoteFailed: 'We could not calculate the price.',
    draftFailed: 'We could not reserve the booking.',
    unavailableProductFallback: 'The product',
    unavailableProductPrefix: 'is not available at',
    unavailableProductAction: 'Go back to add-ons and remove it or choose another time.',
    reviewTitle: 'Summary',
    reviewDesc: 'Your entry, add-ons, and total before payment.',
    jumpTimeLabel: 'Jump time',
    jumpersLabel: 'Number of jumpers',
    createDraft: 'Go to payment',
    pendingTitle: 'Payment pending',
    pendingDesc: 'The booking is reserved in Playground. Payment is connected when Roller payment access is approved.',
    draftStatus: 'Status',
    paymentPending: 'Waiting for payment',
    paymentTitle: 'Pay',
    paymentSetupTitle: 'Preparing payment',
    paymentMethodTitle: 'Payment',
    paymentStarting: 'Starting payment',
    paymentReadyDesc: 'Payment is loading for',
    paymentReceived: 'Payment received',
    paymentReceivedDesc: 'We are waiting for payment confirmation.',
    paymentApprovedTitle: 'Payment complete',
    paymentApprovedDesc: 'We are loading the booking and continuing check-in.',
    paymentFailedTitle: 'Payment stopped',
    paymentFailedDesc: 'The payment could not be completed. Try again or call staff.',
    paymentBlockedTitle: 'Payment unavailable',
    paymentBlockedDesc: 'The payment package could not start for this booking.',
    paymentMissingJwt: 'The booking is missing the Roller payment token.',
    paymentMissingConfig: 'The booking is missing Roller payment configuration.',
    paymentUnknownResult: 'The payment was received but is not finally confirmed.',
    paymentSyncing: 'Loading booking...',
    paymentSyncFailed: 'Payment looks complete but the booking has not synced yet. Try again in a few seconds.',
    paymentRetrySync: 'Load booking again',
    giftCardLabel: 'Gift card',
    giftCardPlaceholder: 'Enter gift card number',
    giftCardHelp: 'Optional. Roller checks the gift card before the booking is reserved.',
    giftCardApplied: 'Applied',
    giftCardRejected: 'Rejected',
    giftCardErrorFallback: 'The gift card could not be used.',
    giftCardFixHint: 'Check the number or remove the gift card to continue.',
    clipCardLabel: 'Clip card',
    clipCardPlaceholder: 'Enter clip-card code',
    clipCardHelp: 'Optional. Works for clip cards such as 10-, 20-, or 30-visit cards. Roller checks which entry products the code covers.',
    clipCardApplied: 'Applied',
    clipCardRejected: 'Rejected',
    clipCardErrorFallback: 'The clip-card code could not be used.',
    clipCardFixHint: 'Check the code or remove it to continue.',
    paymentOptionsTitle: 'Add gift card or clip-card code',
    paymentOptionsApplyGiftCard: 'Apply gift card',
    paymentOptionsApplyClipCard: 'Apply clip card',
    paymentOptionsApplyBoth: 'Apply gift card and clip card',
    paymentOptionsApplyChanges: 'Apply change',
    paymentOptionsUpdateRequired: 'Apply the gift card or clip card before going to payment.',
    paymentCodeReady: 'Ready to apply',
    paymentCodeDone: 'Ready',
    paymentCodeMaxLength: 'Max 32 characters',
    originalTotal: 'Original total',
    noPaymentTitle: 'Booking ready',
    noPaymentDesc: 'The gift card or clip card covers the full amount. We are loading the booking and continuing check-in.',
    noPaymentStatus: 'No card payment needed',
  },
  booking: {
    ref: 'Booking',
    today: 'Today',
    date: 'Date',
    time: 'Time',
    duration: 'Duration',
    guest: 'Guest',
    jumpers: 'Jumpers',
    addons: 'Add-ons',
    none: 'None',
    paidInFull: 'Paid',
    notPaid: 'Unpaid',
    title: 'Your booking',
    subtitle: "Looks right? Let's go.",
    product: 'Product',
    cta: 'Yes, start check-in',
    startingSession: 'Starting check-in…',
    paymentRequiredCta: 'Payment required',
    paymentRequiredHint: 'Payment is built in an upcoming ticket. Please call staff for now.',
    sessionStartFailed: 'We could not start check-in. Try again or call staff.',
    sessionPaymentRequired: 'This booking still has payment due. Please call staff so we can help you continue.',
    sessionWrongDate: 'This booking is for another date. Please call staff so we can check it.',
    sessionAlreadyRedeemed: 'These tickets already look used. Please call staff so we can check the booking.',
    sessionNotFresh: 'We need to update this booking before check-in. Please call staff for now.',
    timeHint: 'Takes about 1–2 min. Next: safety video.',
  },
  safetyVideo: {
    title: 'Safety video',
    description: 'Watch the video before you can continue.',
    play: 'Play',
    playing: 'Video playing…',
    watchFull: 'Watch the full video',
    done: 'Done, continue',
  },
  safetyAttest: {
    title: 'Safety rules',
    description: 'Confirm each rule before continuing.',
    ageRulesTitle: 'Age rules',
    ageRules: {
      adultInArea35: 'Ages 3–5: an adult must accompany the child inside the activity area.',
      adultInVenue610: 'Ages 6–10: may jump alone if a responsible adult is on the premises.',
      canJumpAlone11: 'Ages 11 and up: may jump alone.',
    },
    safetyRulesTitle: 'Safety rules',
    rules: {
      onePerTrampoline: 'Only one person per trampoline – risk of collisions and uncontrollable bounces.',
      avoidEdgePadding: 'Avoid the edge padding – risk of spraining your ankle.',
      landOnBackOrBottom: 'Always land on your bottom or back in foam pits and airbags. Other landings can cause serious injury.',
      tricksWithinAbility: 'Only attempt tricks and flips you can safely perform.',
      noRunning: 'Do not run in the park – risk of collisions and falls.',
    },
    finalAttest: 'I confirm that everyone in my booking has read and understood the rules.',
    cta: 'I understand, continue',
    readyForStaffProcessing: 'Getting staff handoff ready...',
    readyForStaffFailed: 'We could not make this check-in ready for staff. Try again or call staff.',
  },
  addons: {
    title: 'Add-ons',
    description: "Pick extras, skip anything you don't want.",
    alreadyInBooking: 'Already included',
    total: 'Add-ons total',
    perJumper: 'per jumper',
    each: 'each',
    perPerson: 'per person',
    connectedValueProp: 'Most chosen add-on',
    scrollHint: 'add-ons to choose from — scroll down',
    unsupported: 'Coming later',
    unsupportedSelection: 'This add-on cannot be created automatically yet.',
    contactTitle: 'Add-on contact',
    contactDesc: 'Roller requires contact details for the separate add-on booking.',
    quoteFailed: 'We could not calculate the add-on.',
    draftFailed: 'We could not reserve the add-on.',
    reviewTitle: 'Review add-on',
    reviewDesc: 'The price comes directly from the booking system.',
    createDraft: 'Go to payment',
    paymentTitle: 'Pay add-on',
    paymentApprovedTitle: 'Payment complete',
    paymentApprovedDesc: 'The add-on is paid. We are continuing check-in.',
    pendingTitle: 'Payment pending',
    pendingDesc: 'The add-on is reserved as a separate Playground booking. Payment is connected when Roller payment access is approved.',
    products: {
      skyriderLabel: 'SkyRider',
      skyriderDesc: 'Zip-line experience. Requires min 100 cm.',
      connectedLabel: 'Connected',
      connectedDesc: 'Track jumps, leaderboards, highlight reel.',
      coffeeLabel: 'Coffee',
      coffeeDesc: 'Coffee for the grown-ups while the kids jump.',
      extraPersonLabel: 'Extra person',
      extraPersonDesc: 'Add another jumper to this booking.',
      lockLabel: 'Padlock',
      lockDesc: 'Padlock for the lockers.',
      socksLabel: 'Socks',
      socksDesc: 'Jump socks, required.',
    },
  },
  skyrider: {
    title: 'Before SkyRider',
    description: 'Check that every SkyRider pass is used by a guest who meets the requirements.',
    infoLabel: 'SkyRider information',
    requirementTitle: 'Minimum 100 cm',
    requirementText: 'The guest must be at least 100 cm tall to ride.',
    safetyTitle: 'Safety check',
    safetyText: 'Staff make a final safety check before the ride.',
    timingTitle: 'Ride after jump time',
    timingText: 'We recommend using SkyRider after trampoline time so jump time is not interrupted.',
    confirmCheckbox: 'I confirm that SkyRider passes will only be used by guests who are at least 100 cm tall and follow the staff safety check.',
    removeSkyRider: 'Remove SkyRider',
  },
  connected: {
    title: 'Connected profiles',
    description: 'Each Connected band is linked to a profile. Enter names so staff know who gets which band.',
    profile: 'Profile',
    namePlaceholder: 'Name',
    avatar: 'Icon',
    confirm: 'Confirm profiles',
  },
  payment: {
    title: 'Payment',
    description: 'Tap your card on the terminal when ready.',
    booking: 'Booking',
    items: "What you're paying for",
    total: 'Total',
    pay: 'Pay',
    afterPaymentHint: 'After payment you will get a code to show at the entrance.',
    baseProduct: 'Booking',
    addonsLabel: 'Add-ons',
  },
  confirm: {
    title: 'Ready for staff',
    subtitle: 'Show the code below at the entrance. Staff will complete check-in.',
    pickupCode: 'Staff code',
    staffHandout: 'Pick up from staff',
    otherAddons: 'Other add-ons on your booking',
    wristbands: 'Wristbands',
    connectedBands: 'Connected bands',
    complete: 'Done & next guest',
    done: 'Start over',
    showStaffNote: 'Show staff',
    alreadyCheckedInTitle: 'Already checked in',
    alreadyCheckedInSubtitle: 'This booking has already been completed.',
    alreadyCheckedInHelp: 'Call staff if anything looks wrong.',
  },
  print: {
    title: 'Done, head to the park!',
    subtitle: 'Your receipt is printing.',
    printing: 'Printing…',
  },
  present: {
    eyebrow: 'Show at entrance',
    title: 'Ready for the park',
    instruction: 'Show the QR code or staff code to staff to get your wristbands.',
    startOver: 'Start over',
  },
  extend: {
    loading: 'Loading extension…',
    view: {
      title: 'Extend your session',
      subtitle: '+30 minutes of extra jump time.',
      currentEnd: 'Current end',
      newEnd: 'New end',
      price: 'Price',
      cta: 'Pay',
    },
    pay: {
      title: 'Extension payment',
      subtitle: '+30 min for',
      swish: 'Swish',
      card: 'Card',
    },
    qr: {
      eyebrow: 'Band swap',
      title: '+30 minutes confirmed',
      newEndPrefix: 'New end:',
      nextStepLabel: 'Next step',
      nextStepText: 'Go to the cashier or staff to get a new wristband with the updated end time.',
    },
    error: {
      title: "We couldn't load the extension",
      expired: 'This link has expired. Please call staff.',
      already: 'This booking has already been extended.',
      generic: 'Something went wrong. Please call staff.',
    },
  },
};

export type Translations = typeof sv;
const translations: Record<Language, Translations> = { sv, en };

interface LanguageContextValue {
  lang: Language;
  t: Translations;
  toggleLang: () => void;
  setLang: (l: Language) => void;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'sv',
  t: sv,
  toggleLang: () => {},
  setLang: () => {},
});

const STORAGE_KEY = 'jy.lang';

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'sv';
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY) as Language | null;
      return stored === 'sv' || stored === 'en' ? stored : 'sv';
    } catch {}
    return 'sv';
  });

  const setLang = (l: Language) => {
    setLangState(l);
    try {
      localStorage.setItem(STORAGE_KEY, l);
    } catch {}
  };
  const toggleLang = () => setLang(lang === 'sv' ? 'en' : 'sv');

  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggleLang, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  return useContext(LanguageContext);
}
