'use client';
import { createContext, useContext, useEffect, useState } from 'react';
import { weekdayComboCopy } from './weekdayComboCopy';

export type Language = 'sv' | 'en';

const sv = {
  common: {
    back: 'Tillbaka',
    continue: 'Fortsätt',
    confirm: 'Bekräfta',
    cancel: 'Avbryt',
    skip: 'Hoppa över',
    processing: 'Behandlar…',
    loading: 'Laddar…',
    fetchingSlip: 'Vi hämtar din lapp…',
    currency: 'kr',
    done: 'Klart',
    yes: 'Ja',
    no: 'Nej',
    callStaff: 'Hämta personal',
    staffCalled: 'Personal är på väg',
    stillThere: 'Är du kvar?',
    stillThereDesc: 'Tryck var som helst för att fortsätta, annars börjar vi om.',
    imHere: 'Jag är kvar',
    exit: 'Avsluta',
    language: 'Språk',
    switchLanguage: 'Byt språk till',
  },
  exitFlow: {
    title: 'Vill du avsluta?',
    description: 'Dina val på den här enheten tas bort. En bokning eller betalning som redan är klar påverkas inte.',
    confirm: 'Avsluta och gå till start',
    stay: 'Fortsätt här',
  },
  progress: {
    booking: 'Bokning',
    safety: 'Säkerhet',
    extras: 'Tillägg',
    payment: 'Betalning',
    done: 'Klar',
  },
  buyProgress: {
    entry: 'Entré',
    addons: 'Tillägg',
    payment: 'Betalning',
    safety: 'Säkerhet',
    done: 'Klar',
  },
  idle: {
    tap: 'Tryck för att börja',
    line1: 'Välkommen till',
    line2: 'JumpYard',
  },
  start: {
    eyebrowKiosk: 'Kiosk',
    eyebrowPark: 'Park-QR',
    eyebrowSms: 'SMS-länk',
    title: 'Välkommen!',
    subtitle: 'Samma incheckning oavsett hur du kom hit.',
    cta: 'Starta',
  },
  choice: {
    // #495 (Love 2026-10-08): a welcoming heading in the same italic; the last word is red.
    title: 'Redo att',
    titleAccent: 'hoppa?',
    haveBooking: 'Jag har en bokning',
    haveBookingDesc: 'Hitta din bokning och checka in',
    buyTickets: 'Köp entré',
    buyTicketsDesc: 'Köp entré och fortsätt till check-in',
    // #491 (Love 2026-10-08): after "Gör en ny bokning" by mistake, today's number is one tap away.
    backToCheckin: 'Tillbaka till min incheckning',
  },
  lookup: {
    title: 'Hitta din bokning',
    description: 'Skriv in bokningsnummer eller mejl för att hitta din bokning.',
    phoneLookupDisabled: 'Sök med bokningsnummer eller mejl',
    phoneLookupDisabledDesc: 'Det går inte att söka med telefonnummer. Du kan också använda bokningens QR-kod.',
    placeholder: 'Bokningsnummer eller mejl',
    cta: 'Sök',
    notFound: 'Vi hittade ingen bokning idag.',
    tryAgain: 'Kontrollera uppgiften eller hämta personal.',
    paymentRequired: 'Bokningen har kvar att betala.',
    paymentRequiredDesc: 'Hämta personal så hjälper vi dig vidare.',
    wrongDate: 'Bokningen gäller ett annat datum.',
    wrongDateDesc: 'Kontrollera datumet eller hämta personal.',
    noRedeemableTickets: 'Bokningen saknar biljetter att checka in.',
    noRedeemableTicketsDesc: 'Hämta personal så kontrollerar vi bokningen.',
    serviceUnavailable: 'Vi kunde inte nå bokningssystemet.',
    serviceUnavailableDesc: 'Försök igen eller hämta personal.',
    lookupFailed: 'Något gick fel vid sökningen.',
    scanning: 'Skannar…',
  },
  buy: {
    selectTicket: 'Välj biljett',
    selectJumpTime: 'Välj hopptid',
    sectionEntry: 'Entré',
    sectionFamily: 'Familj',
    sectionCombo: weekdayComboCopy.sv.name,
    comboPeople: '2 personer',
    comboDuration: '60 min',
    comboPizza: '1 pizza',
    comboSeason: weekdayComboCopy.sv.availability,
    comboPackageNote: '2 personer',
    entry60: '60 min entré',
    entry90: '90 min entré',
    entry120: '120 min entré',
    family60: '60 min familj',
    family90: '90 min familj',
    family120: '120 min familj',
    perPersonNote: 'Per person',
    familyNote: '4 hoppare, 1 över 18',
    howMany: 'Hur många?',
    quantityJumpers: 'Antal hoppare',
    quantityPackages: 'Antal familjepaket',
    quantityComboPackages: 'Antal combo-paket',
    total: 'Totalt',
    toPay: 'Att betala',
    selectTime: 'Välj starttid',
    selectTimeToday: 'Idag',
    selectTimeDesc: 'Välj när ni vill börja hoppa.',
    startTimeLabel: 'Starttid',
    todaySuffix: 'idag',
    loadingAvailabilityTitle: 'Hämtar tillgängliga platser',
    loadingAvailabilityDesc: 'Vi kontrollerar kapacitet för',
    loadingAvailabilityGeneric: 'Vi kontrollerar kapacitet i Roller.',
    spotsLeft: 'platser kvar',
    spotsFull: 'Fullbokat',
    // #491: the 60-minute spots per start time.
    slotSpotsLeft: '{count} platser kvar',
    slotSpotsLeftOne: '1 plats kvar',
    slotFewLeft: 'Få platser kvar',
    slotFull: 'Fullt',
    slotChecking: 'Kollar lediga platser',
    // #491 round 1 (Love 2026-10-08): the time now, and how soon each start time begins.
    clockNow: 'Klockan är',
    startsIn: 'om {time}',
    startsNow: 'startar nu',
    popular: 'Populärt',
    maxReached: 'Max',
    contactTitle: 'Din kontakt',
    contactDesc: 'Vi skickar bekräftelse och påminnelser.',
    emailLabel: 'E-post',
    emailPlaceholder: 'gäst@exempel.se',
    emailMarketingLabel: 'Ja tack! Mejla mig erbjudanden & nyheter från JumpYard',
    emailMarketingHelp: 'Avsluta när du vill.',
    emailMarketingPrivacy: 'Integritet',
    emailMarketingActive: 'Du är med!',
    emailMarketingNeedEmail: 'Fyll i din e-post först',
    creating: 'Skapar bokning…',
    confirmCreate: 'Bekräfta & fortsätt',
    skipContact: 'Hoppa över',
    availabilityFailed: 'Vi kunde inte hämta lediga tider.',
    retryAvailability: 'Försök igen',
    noProductsAvailableTitle: 'Inga produkter tillgängliga',
    noProductsAvailableDesc: 'Det finns inga bokningsbara produkter för den valda tiden.',
    chooseAnotherTime: 'Välj en annan tid',
    spotsAvailable: 'Ledigt',
    firstNameLabel: 'Förnamn',
    lastNameLabel: 'Efternamn',
    phoneLabel: 'Telefon',
    phonePlaceholder: 'Ditt telefonnummer',
    contactDetailsRequiredTitle: 'Vi behöver lite fler uppgifter',
    contactDetailsRequiredDesc: 'Fyll i efternamn och telefonnummer för att gå vidare.',
    quoting: 'Räknar pris…',
    quoteFailed: 'Vi kunde inte räkna ut priset.',
    draftFailed: 'Vi kunde inte reservera bokningen.',
    unavailableProductFallback: 'Produkten',
    unavailableProductPrefix: 'är inte tillgänglig kl.',
    unavailableProductAction: 'Gå tillbaka till tillägg och ta bort valet eller välj en annan tid.',
    jumpTimeLabel: 'Hopptid',
    jumpersLabel: 'Hoppare',
    createDraft: 'Gå till betalning',
    createDraftFree: 'Slutför bokning',
    pendingTitle: 'Betalning väntar',
    pendingDesc: 'Bokningen är reserverad i Playground. Betalningssteget kopplas in när Roller-betalningen är godkänd.',
    draftStatus: 'Status',
    paymentPending: 'Väntar på betalning',
    paymentTitle: 'Betala',
    paymentSetupTitle: 'Förbereder betalning',
    paymentMethodTitle: 'Betalning',
    paymentStarting: 'Startar betalning',
    paymentReadyDesc: 'Betalningen laddas för',
    paymentReceived: 'Betalning mottagen',
    paymentReceivedDesc: 'Vi väntar på bekräftelse från betalningen.',
    paymentApprovedTitle: 'Betalning klar',
    paymentApprovedDesc: 'Vi synkar bokningen. Roller skickar bekräftelse och kvitto till e-posten på bokningen.',
    paymentFailedTitle: 'Betalningen stoppades',
    paymentFailedDesc: 'Betalningen kunde inte slutföras. Dina val finns kvar och du kan välja ett annat betalsätt.',
    paymentRecoveryTitle: 'Vi kan inte bekräfta betalningen ännu',
    paymentRecoveryDescription: 'Betala inte igen för samma köp. Kontrollera status igen om en stund. Om problemet kvarstår hjälper vi dig att kontrollera köpet på plats när du kommer till JumpYard.',
    paymentRetryMethod: 'Välj ett annat betalsätt',
    paymentCheckStatus: 'Kontrollera betalningen',
    paymentChecking: 'Vi kontrollerar betalningen',
    paymentBlockedTitle: 'Betalning saknas',
    paymentBlockedDesc: 'Betalningspaketet kunde inte startas för den här bokningen.',
    paymentMissingJwt: 'Bokningen saknar betalningstoken från Roller.',
    paymentMissingConfig: 'Bokningen saknar betalningskonfiguration från Roller.',
    paymentUnknownResult: 'Betalningen är mottagen men inte slutligt bekräftad.',
    paymentSyncing: 'Betalning genomförd',
    paymentSyncLoader: 'Hämtar bokningen...',
    paymentSyncFailed: 'Betalningen är klar men bokningen har inte hunnit synkas.',
    paymentSyncFallback: 'Kontrollera igen om en stund. Om problemet kvarstår hjälper vi dig att kontrollera köpet på plats när du kommer till JumpYard.',
    paymentRetrySync: 'Hämta bokningen igen',
    giftCardLabel: 'Presentkort',
    giftCardPlaceholder: 'Ange kortnummer',
    clipCardLabel: 'Rabattkod eller klippkort',
    clipCardPlaceholder: 'Ange rabattkod',
    memberCodeLabel: 'Medlemskod',
    memberCodePlaceholder: 'Ange medlemskod',
    paymentCodeAcceptedTitle: 'Koden är godkänd',
    giftCardAcceptedTitle: 'Presentkortet är godkänt',
    paymentCodeAcceptedDetail: 'dras av från priset.',
    paymentCodeRejectedTitle: 'Koden kunde inte användas',
    giftCardRejectedTitle: 'Presentkortet kunde inte användas',
    paymentCodeRejectedDetail: 'Kontrollera koden, ta bort den eller fortsätt utan.',
    paymentCodeCheckedOnContinue: 'Koden kontrolleras när du går vidare.',
    codeRejectedDialogBody: 'Vill du fortsätta utan kod och betala ordinarie pris?',
    codeRejectedContinueWithout: 'Fortsätt utan kod',
    codeRejectedEditCode: 'Ändra kod',
    paymentOptionsTitle: 'Rabattkod, medlem eller presentkort',
    paymentOptionTypeQuestion: 'Vad vill du använda?',
    paymentOptionTypeDiscount: 'Rabattkod',
    paymentOptionTypeMember: 'Medlem',
    paymentOptionTypeGiftCard: 'Presentkort',
    paymentOptionClipCardHint: 'Gäller även klippkort.',
    paymentOptionRemove: 'Ta bort koden',
    paymentOptionsApply: 'Applicera',
    paymentOptionsChecking: 'Kontrollerar…',
    paymentOptionsFailed: 'Koden kunde inte kontrolleras. Försök igen.',
    paymentOptionsContactRequired: 'Fyll i giltiga kontaktuppgifter ovan för att applicera.',
    paymentCodeMaxLength: 'Max 32 tecken',
    originalTotal: 'Ordinarie total',
    noPaymentTitle: 'Bokning klar',
    noPaymentDesc: 'Presentkortet eller koden täcker hela beloppet. Vi hämtar bokningen och fortsätter check-in.',
    noPaymentStatus: 'Ingen kortbetalning behövs',
  },
  buyRecovery: {
    title: 'Vi hittade din senaste check-in.',
    description: 'Fortsätt där du var.',
    checking: 'Hämtar bokningen',
    failedTitle: 'Vi hittade din senaste check-in.',
    failedDescription: 'Bokningen är sparad här, men vi kunde inte hämta den just nu. Försök igen eller börja om.',
    completedUnavailableTitle: 'Vi kan inte visa din tidigare bokning',
    completedUnavailableDescription: 'Du hade redan slutfört bokningen, men vi kan inte hämta den just nu. Försök igen för att visa den, eller gör en ny bokning.',
    unsafeDescription: 'Vi hittade en sparad check-in, men den saknar bokningsnummer. Börja om så skapar vi en ny säker väg.',
    retry: 'Försök igen',
    startOver: 'Börja om',
  },
  booking: {
    ref: 'Bokning',
    today: 'Idag',
    date: 'Datum',
    time: 'Tid',
    duration: 'Längd',
    guest: 'Gäst',
    jumpers: 'Hoppare',
    tickets: 'Biljetter',
    addons: 'Tillägg',
    none: 'Inga',
    paidInFull: 'Betald',
    notPaid: 'Obetald',
    title: 'Din bokning',
    subtitle: 'Ser det rätt ut? Då kör vi.',
    product: 'Produkt',
    cta: 'Ja, starta incheckning',
    startingSession: 'Startar incheckning…',
    paymentRequiredCta: 'Betalning krävs',
    paymentRequiredHint: 'Betalning byggs i en kommande ticket. Hämta personal tills vidare.',
    partiallyPaid: 'Delvis betald',
    checkInAtRegisterCta: 'Checka in i kassan',
    checkInAtRegisterHint: 'Den här bokningen behöver checkas in i kassan.',
    sessionStartFailed: 'Vi kunde inte starta incheckningen. Försök igen eller hämta personal.',
    sessionPaymentRequired: 'Bokningen har kvar att betala. Hämta personal så hjälper vi dig vidare.',
    sessionWrongDate: 'Bokningen gäller ett annat datum. Hämta personal så kontrollerar vi bokningen.',
    sessionAlreadyRedeemed: 'Biljetterna verkar redan vara använda. Hämta personal så kontrollerar vi bokningen.',
    sessionNotFresh: 'Vi behöver uppdatera bokningen innan incheckning. Hämta personal tills vidare.',
    // GH-456 (D0230): check-in opens two hours before the booked start and closes when the session ends.
    // Love, 2026-10-06: a short title that jumps out and one line that says what to do.
    sessionTooEarly: 'Incheckningen öppnar {time}',
    sessionTooEarlyNoTime: 'För tidigt att checka in',
    sessionTooEarlyHint: 'Två timmar före ert pass.',
    sessionTooLate: 'Er hopptid är slut',
    sessionTooLateHint: 'Gå till kassan så hjälper vi er.',
    timeHint: 'Tar ca 1–2 min. Nästa steg: säkerhetsvideo.',
  },
  safetyVideo: {
    title: 'Säkerhetsgenomgång',
    description: 'Titta på videon tillsammans med alla som ska hoppa.',
    buyTitle: 'Säkerhetsgenomgång',
    buyDescription: 'Titta på videon tillsammans med alla som ska hoppa.',
    play: 'Spela upp',
    playing: 'Videon spelas…',
    loading: 'Laddar säkerhetsvideon',
    paused: 'Videon är pausad',
    resume: 'Fortsätt titta',
    errorTitle: 'Videon kunde inte spelas upp',
    errorDescription: 'Kontrollera uppkopplingen och försök igen.',
    retry: 'Försök igen',
    staffHelp: 'Be personalen på plats om hjälp med säkerhetsgenomgången om problemet kvarstår.',
    watchFull: 'Titta hela videon',
    replay: 'Se videon igen',
    durationBadge: 'ca {seconds} sek',
  },
  // #458: one approval under the film. Short rules; the button carries the approved attestation.
  safetyAttest: {
    safetyRulesTitle: 'Säkerhetsregler',
    shortRules: {
      ageRules: ['3–5 år: vuxen med på hoppytan', '6–10 år: vuxen i lokalen', '11 år och uppåt: hoppar själv'],
      onePerTrampoline: 'En person per trampolin',
      avoidEdgePadding: 'Undvik kantskydden',
      landOnBackOrBottom: 'Landa på rumpa eller rygg i foampit och airbag',
      tricksWithinAbility: 'Gör bara tricks och volter du klarar',
      noRunning: 'Spring inte i parken',
    },
    attestLead: 'Jag intygar',
    attestRest: 'att samtliga i min bokning har tagit del av reglerna och förstått dem.',
    readyForStaffProcessing: 'G\u00f6r redo f\u00f6r personal...',
    readyForStaffFailed: 'Vi kunde inte g\u00f6ra incheckningen redo f\u00f6r personal. F\u00f6rs\u00f6k igen eller h\u00e4mta personal.',
    paymentConfirmationWaiting: 'Betalningen \u00e4r genomf\u00f6rd. Vi v\u00e4ntar p\u00e5 att bokningssystemet bekr\u00e4ftar bokningen, det kan ta upp till n\u00e5gon minut.',
    paymentConfirmationDelayed: 'Bokningen är ännu inte bekräftad. Betala inte igen. Kontrollera igen om en stund. Om problemet kvarstår hjälper vi dig på plats när du kommer till JumpYard.',
    paymentConfirmationRetry: 'Kontrollera igen',
  },
  addons: {
    title: 'Tillägg',
    choices: {
      preview: 'Testläge · testpriser · inga riktiga köp',
      firstGroup: 'Ta med egna eller köp här',
      // #491: socks moved to the quantity step, so the purchase shows only the bottle here.
      firstGroupBottle: 'Ta med egen eller köp här',
      waterRecommended: 'Rekommenderas',
      optionalGroup: 'Valfritt',
      // #491 (Love 2026-10-08): the socks are called JumpSocks everywhere, with one rule text, on the
      // quantity step of a purchase and on the add-on step of an existing booking.
      socksTitle: 'JumpSocks',
      socksBenefit: 'Halkfria strumpor är obligatoriska i JumpYard och måste bäras av alla i trampolinområdet, även icke-hoppande föräldrar.',
      bottleTitle: 'Vattenflaska',
      bottleEnvironment: 'Inga engångsmuggar av miljöskäl.',
      lockBenefit: 'Lås in dina saker medan du hoppar.',
      coffeeBenefit: 'En god paus mellan hoppen.',
      skyRiderBenefit: 'Se parken från ovan i vår höghöjdsbana.',
      skyRiderFact: 'Höghöjdsbana',
      lockFact: 'Till skåpen',
      coffeeFact: 'Nybryggt',
      recommended: 'Vårt tips',
      included: '{count} ingår',
      extraPrice: 'Extra {price}',
      chosen: 'Valt: {count}',
      quantity: 'Antal att lägga till',
      perPair: '{price}/par',
      perEach: '{price}/st',
      perJumper: '{price}/hoppare',
      add: 'Lägg till',
      remove: 'Ta bort',
      unavailableRequired: 'Kan inte köpas här just nu. Har ni inte med egna, fråga personalen.',
    },
    description: 'Välj till extra, hoppa över det du inte vill ha.',
    loading: 'H\u00e4mtar till\u00e4gg',
    socksSectionTitle: 'Godkända hoppstrumpor',
    socksHelp: 'Alla som vistas i parken behöver godkända hoppstrumpor.',
    socksAlreadyHave: 'Vi har redan godkända hoppstrumpor.',
    socksAddPrompt: 'Lägg till de strumpor ni behöver.',
    socksRecommendedCount: 'Rekommenderat antal',
    socksSelectedCount: 'Valt',
    waterBottleSectionTitle: 'Vattenflaska',
    waterBottleHelp: 'Har du med egen vattenflaska? Tyvärr kan vi inte dela ut engångsmuggar av miljöskäl.',
    waterBottleAlreadyHave: 'Vi har med egen vattenflaska.',
    alreadyInBooking: 'Ingår redan',
    total: 'Tillägg totalt',
    perJumper: 'per hoppare',
    each: 'st',
    eachLong: 'styck',
    perPerson: 'per person',
    connectedValueProp: 'Mest valt tillägg',
    unsupported: 'Kommer senare',
    unsupportedSelection: 'Det tillägget kan inte skapas automatiskt ännu.',
    contactTitle: 'Kontakt för tillägget',
    contactDesc: 'Roller kräver kontaktuppgifter för den separata tilläggsbokningen.',
    quoteFailed: 'Vi kunde inte räkna ut tillägget.',
    draftFailed: 'Vi kunde inte reservera tillägget.',
    reviewTitle: 'Kontrollera tillägg',
    reviewDesc: 'Priset hämtas direkt från bokningssystemet.',
    createDraft: 'Gå till betalning',
    paymentTitle: 'Betala tillägg',
    paymentApprovedTitle: 'Betalning klar',
    paymentApprovedDesc: 'Tillägget är betalt. Roller skickar bekräftelse och kvitto till e-posten på bokningen.',
    pendingTitle: 'Betalning väntar',
    pendingDesc: 'Tillägget är reserverat som en separat Playground-bokning. Betalningssteget kopplas in när Roller-betalningen är godkänd.',
    products: {
      skyriderLabel: 'SkyRider',
      skyriderDesc: 'Linbane-upplevelsen. Kräver min 125 cm.',
      connectedLabel: 'Connected',
      connectedDesc: 'Spåra hopp, tävla på topplistor, få highlight-klipp.',
      coffeeLabel: 'Bryggkaffe',
      coffeeDesc: 'Kaffe åt de vuxna medan barnen hoppar.',
      extraPersonLabel: 'Extra person',
      extraPersonDesc: 'Lägg till en till hoppare.',
      lockLabel: 'Hänglås',
      lockDesc: 'Hänglås till skåpen.',
      socksLabel: 'Strumpor',
      socksDesc: 'Hoppstrumpor, obligatoriska.',
      waterBottleLabel: 'Vattenflaska',
      waterBottleDesc: 'Köp till en flaska eller bekräfta att ni har med egen.',
    },
  },
  skyrider: {
    title: 'Innan SkyRider',
    description: 'Kolla höjdkravet och när SkyRider passar bäst.',
    infoLabel: 'SkyRider-information',
    requirementTitle: 'Minst 125 cm',
    requirementText: 'Alla som åker SkyRider behöver vara minst 125 cm.',
    timingTitle: 'Passar bäst efter hopptiden',
    timingText: 'Vi rekommenderar att SkyRider görs efter hoppasset.',
    confirmCheckbox: 'Jag bekräftar att alla SkyRider-åkare är minst 125 cm.',
    removeSkyRider: 'Ta bort SkyRider',
  },
  connected: {
    title: 'Connected-profiler',
    description: 'Varje Connected-band kopplas till en profil. Skriv namn så personalen vet vem som får vilket band.',
    profile: 'Profil',
    namePlaceholder: 'Namn',
    avatar: 'Ikon',
    confirm: 'Bekräfta profiler',
  },
  payment: {
    title: 'Betalning',
    description: 'Håll kortet mot terminalen när du är redo.',
    booking: 'Bokning',
    items: 'Vad du betalar för',
    total: 'Totalt',
    pay: 'Betala',
    afterPaymentHint: 'Efter betalning fortsätter du till entrén.',
    baseProduct: 'Bokning',
    addonsLabel: 'Tillägg',
  },
  confirm: {
    title: 'Redo för entrén',
    subtitle: 'Hämta armband hos personalen.',
    onsiteSubtitle: 'Hämta armband hos personalen.',
    smsSubtitle: 'Gå till personalen när ni kommer till parken.',
    kioskSubtitle: 'Ta utskriften och visa den när ni hämtar armband.',
    pickupCode: 'Bokning',
    handoffTitle: 'Visa vid entrén',
    handoffCode: 'Handoff-kod',
    qrHelp: 'Visa QR-koden för personalen. Det går också bra med namn eller e-post.',
    entryTicketFallback: 'Entré',
    staffHandout: 'Att hämta',
    otherAddons: 'Övrigt i bokningen',
    wristbands: 'Armband',
    connectedBands: 'Connected-band',
    complete: 'Klart & nästa gäst',
    done: 'Gör en ny bokning',
    showStaffNote: 'Visa personalen',
    alreadyCheckedInTitle: 'Redan incheckad',
    alreadyCheckedInSubtitle: 'Den här bokningen är redan slutförd.',
    alreadyCheckedInHelp: 'Hämta personal om något inte stämmer.',
  },
  print: {
    title: 'Klart, gå till banan!',
    subtitle: 'Ditt kvitto skrivs ut.',
    printing: 'Skriver ut…',
  },
  present: {
    eyebrow: 'Visa vid entrén',
    title: 'Redo för parken',
    instruction: 'Gå till personalen för att få armband.',
    startOver: 'Börja om',
  },
  extend: {
    loading: 'Laddar förlängning…',
    view: {
      title: 'Förläng din session',
      subtitle: '+30 minuter extra hopptid.',
      currentEnd: 'Nuvarande sluttid',
      newEnd: 'Ny sluttid',
      price: 'Pris',
      cta: 'Betala',
    },
    pay: {
      title: 'Betala förlängning',
      subtitle: '+30 min för',
      swish: 'Swish',
      card: 'Kort',
    },
    qr: {
      eyebrow: 'Bandbyte',
      title: '+30 minuter bekräftat',
      newEndPrefix: 'Ny sluttid:',
      nextStepLabel: 'Nästa steg',
      nextStepText: 'Gå till kassan eller personalen för att få ett nytt band med uppdaterad sluttid.',
    },
    error: {
      title: 'Vi kunde inte ladda förlängningen',
      expired: 'Länken har gått ut. Hämta personal.',
      already: 'Den här bokningen är redan förlängd.',
      generic: 'Något gick fel. Hämta personal.',
    },
  },
};

const en: typeof sv = {
  common: {
    back: 'Back',
    continue: 'Continue',
    confirm: 'Confirm',
    cancel: 'Cancel',
    skip: 'Skip',
    processing: 'Processing…',
    loading: 'Loading…',
    fetchingSlip: 'Fetching your slip…',
    currency: 'kr',
    done: 'Done',
    yes: 'Yes',
    no: 'No',
    callStaff: 'Call staff',
    staffCalled: 'Staff is on the way',
    stillThere: 'Are you still there?',
    stillThereDesc: 'Tap anywhere to continue, otherwise we restart.',
    imHere: "I'm here",
    exit: 'Exit',
    language: 'Language',
    switchLanguage: 'Switch language to',
  },
  exitFlow: {
    title: 'Do you want to exit?',
    description: 'Your choices on this device are removed. A booking or payment that is already complete is not affected.',
    confirm: 'Exit and go to start',
    stay: 'Stay here',
  },
  progress: {
    booking: 'Booking',
    safety: 'Safety',
    extras: 'Extras',
    payment: 'Payment',
    done: 'Done',
  },
  buyProgress: {
    entry: 'Entry',
    addons: 'Add-ons',
    payment: 'Payment',
    safety: 'Safety',
    done: 'Done',
  },
  idle: {
    tap: 'Tap to start',
    line1: 'Welcome to',
    line2: 'JumpYard',
  },
  start: {
    eyebrowKiosk: 'Kiosk',
    eyebrowPark: 'Park QR',
    eyebrowSms: 'SMS Link',
    title: 'Welcome!',
    subtitle: 'Same check-in whichever way you arrived.',
    cta: 'Start',
  },
  choice: {
    title: 'Ready to',
    titleAccent: 'jump?',
    haveBooking: 'I have a booking',
    haveBookingDesc: 'Find your booking and check in',
    buyTickets: 'Buy entry',
    buyTicketsDesc: 'Buy entry and continue to check-in',
    backToCheckin: 'Back to my check-in',
  },
  lookup: {
    title: 'Find your booking',
    description: 'Enter booking number or email to find your booking.',
    phoneLookupDisabled: 'Search with a booking number or email',
    phoneLookupDisabledDesc: 'Phone-number search is unavailable. You can also use the booking QR code.',
    placeholder: 'Booking number or email',
    cta: 'Search',
    notFound: "We couldn't find a booking today.",
    tryAgain: 'Check the details or call staff.',
    paymentRequired: 'This booking still has payment due.',
    paymentRequiredDesc: 'Please call staff so we can help you continue.',
    wrongDate: 'This booking is for another date.',
    wrongDateDesc: 'Check the date or call staff.',
    noRedeemableTickets: 'This booking has no tickets to check in.',
    noRedeemableTicketsDesc: 'Please call staff so we can check the booking.',
    serviceUnavailable: "We couldn't reach the booking system.",
    serviceUnavailableDesc: 'Try again or call staff.',
    lookupFailed: 'Something went wrong during lookup.',
    scanning: 'Scanning…',
  },
  buy: {
    selectTicket: 'Select ticket',
    selectJumpTime: 'Choose jump time',
    sectionEntry: 'Entry',
    sectionFamily: 'Family',
    sectionCombo: weekdayComboCopy.en.name,
    comboPeople: '2 people',
    comboDuration: '60 min',
    comboPizza: '1 pizza',
    comboSeason: weekdayComboCopy.en.availability,
    comboPackageNote: '2 people',
    entry60: '60 min entry',
    entry90: '90 min entry',
    entry120: '120 min entry',
    family60: '60 min family',
    family90: '90 min family',
    family120: '120 min family',
    perPersonNote: 'Per person',
    familyNote: '4 jumpers, 1 adult 18+',
    howMany: 'How many?',
    quantityJumpers: 'Number of jumpers',
    quantityPackages: 'Number of family packages',
    quantityComboPackages: 'Number of combo packages',
    total: 'Total',
    toPay: 'To pay',
    selectTime: 'Choose start time',
    selectTimeToday: 'Today',
    selectTimeDesc: 'Choose when you want to start jumping.',
    startTimeLabel: 'Start time',
    todaySuffix: 'today',
    loadingAvailabilityTitle: 'Loading available spots',
    loadingAvailabilityDesc: 'Checking capacity for',
    loadingAvailabilityGeneric: 'Checking capacity in Roller.',
    spotsLeft: 'spots left',
    spotsFull: 'Fully booked',
    slotSpotsLeft: '{count} spots left',
    slotSpotsLeftOne: '1 spot left',
    slotFewLeft: 'Few spots left',
    slotFull: 'Full',
    slotChecking: 'Checking free spots',
    clockNow: 'The time is',
    startsIn: 'in {time}',
    startsNow: 'starts now',
    popular: 'Popular',
    maxReached: 'Max',
    contactTitle: 'Your contact',
    contactDesc: 'We send confirmation and reminders.',
    emailLabel: 'Email',
    emailPlaceholder: 'guest@example.com',
    emailMarketingLabel: 'Yes please! Email me offers & news from JumpYard',
    emailMarketingHelp: 'Unsubscribe anytime.',
    emailMarketingPrivacy: 'Privacy',
    emailMarketingActive: "You're in!",
    emailMarketingNeedEmail: 'Enter your email first',
    creating: 'Creating booking…',
    confirmCreate: 'Confirm & continue',
    skipContact: 'Skip',
    availabilityFailed: 'We could not load available times.',
    retryAvailability: 'Try again',
    noProductsAvailableTitle: 'No products available',
    noProductsAvailableDesc: 'There are no bookable products for the selected time.',
    chooseAnotherTime: 'Choose another time',
    spotsAvailable: 'Available',
    firstNameLabel: 'First name',
    lastNameLabel: 'Last name',
    phoneLabel: 'Phone',
    phonePlaceholder: 'Your phone number',
    contactDetailsRequiredTitle: 'We need a little more information',
    contactDetailsRequiredDesc: 'Add your last name and phone number to continue.',
    quoting: 'Calculating price…',
    quoteFailed: 'We could not calculate the price.',
    draftFailed: 'We could not reserve the booking.',
    unavailableProductFallback: 'The product',
    unavailableProductPrefix: 'is not available at',
    unavailableProductAction: 'Go back to add-ons and remove it or choose another time.',
    jumpTimeLabel: 'Jump time',
    jumpersLabel: 'Jumpers',
    createDraft: 'Go to payment',
    createDraftFree: 'Complete booking',
    pendingTitle: 'Payment pending',
    pendingDesc: 'The booking is reserved in Playground. Payment is connected when Roller payment access is approved.',
    draftStatus: 'Status',
    paymentPending: 'Waiting for payment',
    paymentTitle: 'Pay',
    paymentSetupTitle: 'Preparing payment',
    paymentMethodTitle: 'Payment',
    paymentStarting: 'Starting payment',
    paymentReadyDesc: 'Payment is loading for',
    paymentReceived: 'Payment received',
    paymentReceivedDesc: 'We are waiting for payment confirmation.',
    paymentApprovedTitle: 'Payment complete',
    paymentApprovedDesc: 'We are syncing the booking. Roller sends the confirmation and receipt to the booking email.',
    paymentFailedTitle: 'Payment stopped',
    paymentFailedDesc: 'The payment could not be completed. Your choices are saved and you can choose another payment method.',
    paymentRecoveryTitle: 'We cannot confirm the payment yet',
    paymentRecoveryDescription: 'Do not pay again for the same purchase. Check the status again in a moment. If the problem continues, we will help you check the purchase when you arrive at JumpYard.',
    paymentRetryMethod: 'Choose another payment method',
    paymentCheckStatus: 'Check payment status',
    paymentChecking: 'Checking your payment',
    paymentBlockedTitle: 'Payment unavailable',
    paymentBlockedDesc: 'The payment package could not start for this booking.',
    paymentMissingJwt: 'The booking is missing the Roller payment token.',
    paymentMissingConfig: 'The booking is missing Roller payment configuration.',
    paymentUnknownResult: 'The payment was received but is not finally confirmed.',
    paymentSyncing: 'Payment complete',
    paymentSyncLoader: 'Loading booking...',
    paymentSyncFailed: 'Payment is complete but the booking has not synced yet.',
    paymentSyncFallback: 'Check again in a moment. If the problem continues, we will help you check the purchase when you arrive at JumpYard.',
    paymentRetrySync: 'Load booking again',
    giftCardLabel: 'Gift card',
    giftCardPlaceholder: 'Enter card number',
    clipCardLabel: 'Discount code or clip card',
    clipCardPlaceholder: 'Enter discount code',
    memberCodeLabel: 'Member code',
    memberCodePlaceholder: 'Enter member code',
    paymentCodeAcceptedTitle: 'Code accepted',
    giftCardAcceptedTitle: 'Gift card accepted',
    paymentCodeAcceptedDetail: 'is deducted from the price.',
    paymentCodeRejectedTitle: 'The code could not be used',
    giftCardRejectedTitle: 'The gift card could not be used',
    paymentCodeRejectedDetail: 'Check the code, remove it or continue without it.',
    paymentCodeCheckedOnContinue: 'The code is checked when you continue.',
    codeRejectedDialogBody: 'Do you want to continue without the code and pay the regular price?',
    codeRejectedContinueWithout: 'Continue without code',
    codeRejectedEditCode: 'Change code',
    paymentOptionsTitle: 'Discount, member or gift card',
    paymentOptionTypeQuestion: 'What would you like to use?',
    paymentOptionTypeDiscount: 'Discount',
    paymentOptionTypeMember: 'Member',
    paymentOptionTypeGiftCard: 'Gift card',
    paymentOptionClipCardHint: 'Also for clip cards.',
    paymentOptionRemove: 'Remove code',
    paymentOptionsApply: 'Apply',
    paymentOptionsChecking: 'Checking…',
    paymentOptionsFailed: 'The code could not be checked. Please try again.',
    paymentOptionsContactRequired: 'Enter valid contact details above to apply.',
    paymentCodeMaxLength: 'Max 32 characters',
    originalTotal: 'Original total',
    noPaymentTitle: 'Booking ready',
    noPaymentDesc: 'The gift card or code covers the full amount. We are loading the booking and continuing check-in.',
    noPaymentStatus: 'No card payment needed',
  },
  buyRecovery: {
    title: 'We found your latest check-in.',
    description: 'Continue where you left off.',
    checking: 'Loading booking',
    failedTitle: 'We found your latest check-in.',
    failedDescription: 'The booking is saved here, but we could not load it right now. Try again or start over.',
    completedUnavailableTitle: 'We cannot show your previous booking',
    completedUnavailableDescription: 'You had already completed the booking, but we cannot load it right now. Try again to view it, or make a new booking.',
    unsafeDescription: 'We found a saved check-in, but it is missing a booking number. Start over to create a new safe path.',
    retry: 'Try again',
    startOver: 'Start over',
  },
  booking: {
    ref: 'Booking',
    today: 'Today',
    date: 'Date',
    time: 'Time',
    duration: 'Duration',
    guest: 'Guest',
    jumpers: 'Jumpers',
    tickets: 'Tickets',
    addons: 'Add-ons',
    none: 'None',
    paidInFull: 'Paid',
    notPaid: 'Unpaid',
    title: 'Your booking',
    subtitle: "Looks right? Let's go.",
    product: 'Product',
    cta: 'Yes, start check-in',
    startingSession: 'Starting check-in…',
    paymentRequiredCta: 'Payment required',
    paymentRequiredHint: 'Payment is built in an upcoming ticket. Please call staff for now.',
    partiallyPaid: 'Partially paid',
    checkInAtRegisterCta: 'Check in at the register',
    checkInAtRegisterHint: 'This booking needs to be checked in at the register.',
    sessionStartFailed: 'We could not start check-in. Try again or call staff.',
    sessionPaymentRequired: 'This booking still has payment due. Please call staff so we can help you continue.',
    sessionWrongDate: 'This booking is for another date. Please call staff so we can check it.',
    sessionAlreadyRedeemed: 'These tickets already look used. Please call staff so we can check the booking.',
    sessionNotFresh: 'We need to update this booking before check-in. Please call staff for now.',
    sessionTooEarly: 'You can check in from {time}',
    sessionTooEarlyNoTime: 'Too early to check in',
    sessionTooEarlyHint: 'Two hours before your session.',
    sessionTooLate: 'Your jump time has ended',
    sessionTooLateHint: 'Go to the front desk and we will help you.',
    timeHint: 'Takes about 1–2 min. Next: safety video.',
  },
  safetyVideo: {
    title: 'Safety video',
    description: 'Watch the video together with everyone who will jump.',
    buyTitle: 'Safety walkthrough',
    buyDescription: 'Watch the video together with everyone who will jump.',
    play: 'Play',
    playing: 'Video playing…',
    loading: 'Loading the safety video',
    paused: 'Video paused',
    resume: 'Continue watching',
    errorTitle: 'The video could not play',
    errorDescription: 'Check your connection and try again.',
    retry: 'Try again',
    staffHelp: 'If the problem continues, ask staff at the park for help with the safety briefing.',
    watchFull: 'Watch the full video',
    replay: 'Watch again',
    durationBadge: 'about {seconds} sec',
  },
  safetyAttest: {
    safetyRulesTitle: 'Safety rules',
    shortRules: {
      ageRules: ['Ages 3–5: adult on the jump floor', 'Ages 6–10: adult on site', 'Ages 11 and up: jump alone'],
      onePerTrampoline: 'One person per trampoline',
      avoidEdgePadding: 'Avoid the edge padding',
      landOnBackOrBottom: 'Land on your bottom or back in foam pits and airbags',
      tricksWithinAbility: 'Only do tricks and flips you can manage',
      noRunning: 'No running in the park',
    },
    attestLead: 'I confirm',
    attestRest: 'that everyone in my booking has read and understood the rules.',
    readyForStaffProcessing: 'Getting staff handoff ready...',
    readyForStaffFailed: 'We could not make this check-in ready for staff. Try again or call staff.',
    paymentConfirmationWaiting: 'Your payment is complete. We are waiting for the booking system to confirm the booking, which can take up to a minute or so.',
    paymentConfirmationDelayed: 'The booking is not confirmed yet. Do not pay again. Check again in a moment. If the problem continues, we will help you when you arrive at JumpYard.',
    paymentConfirmationRetry: 'Check again',
  },
  addons: {
    title: 'Add-ons',
    choices: {
      preview: 'Preview · sample prices · no real purchases',
      firstGroup: 'Bring your own or buy here',
      firstGroupBottle: 'Bring your own or buy here',
      waterRecommended: 'Recommended',
      optionalGroup: 'Optional',
      socksTitle: 'JumpSocks',
      socksBenefit: "Non-slip socks are required at JumpYard and must be worn by everyone in the trampoline area, including parents who aren't jumping.",
      bottleTitle: 'Water bottle',
      bottleEnvironment: 'No disposable cups, to reduce waste.',
      lockBenefit: 'Lock away your things while you jump.',
      coffeeBenefit: 'A tasty break between jumps.',
      skyRiderBenefit: 'See the park from above on our high ropes course.',
      skyRiderFact: 'High ropes',
      lockFact: 'For the lockers',
      coffeeFact: 'Freshly brewed',
      recommended: 'Our pick',
      included: '{count} included',
      extraPrice: 'Extra {price}',
      chosen: 'Selected: {count}',
      quantity: 'Quantity to add',
      perPair: '{price}/pair',
      perEach: '{price} each',
      perJumper: '{price}/jumper',
      add: 'Add',
      remove: 'Remove',
      unavailableRequired: 'Not available to buy here right now. If you did not bring your own, ask our staff.',
    },
    description: "Pick extras, skip anything you don't want.",
    loading: 'Loading add-ons',
    socksSectionTitle: 'Approved jump socks',
    socksHelp: 'Everyone in the park needs approved jump socks.',
    socksAlreadyHave: 'We already have approved jump socks.',
    socksAddPrompt: 'Add the socks you need.',
    socksRecommendedCount: 'Recommended count',
    socksSelectedCount: 'Selected',
    waterBottleSectionTitle: 'Water bottle',
    waterBottleHelp: 'Do you have your own water bottle? Sorry, we cannot hand out disposable cups for environmental reasons.',
    waterBottleAlreadyHave: 'We brought our own water bottle.',
    alreadyInBooking: 'Already included',
    total: 'Add-ons total',
    perJumper: 'per jumper',
    each: 'each',
    eachLong: 'each',
    perPerson: 'per person',
    connectedValueProp: 'Most chosen add-on',
    unsupported: 'Coming later',
    unsupportedSelection: 'This add-on cannot be created automatically yet.',
    contactTitle: 'Add-on contact',
    contactDesc: 'Roller requires contact details for the separate add-on booking.',
    quoteFailed: 'We could not calculate the add-on.',
    draftFailed: 'We could not reserve the add-on.',
    reviewTitle: 'Review add-on',
    reviewDesc: 'The price comes directly from the booking system.',
    createDraft: 'Go to payment',
    paymentTitle: 'Pay add-on',
    paymentApprovedTitle: 'Payment complete',
    paymentApprovedDesc: 'The add-on is paid. Roller sends the confirmation and receipt to the booking email.',
    pendingTitle: 'Payment pending',
    pendingDesc: 'The add-on is reserved as a separate Playground booking. Payment is connected when Roller payment access is approved.',
    products: {
      skyriderLabel: 'SkyRider',
      skyriderDesc: 'Zip-line experience. Requires min 125 cm.',
      connectedLabel: 'Connected',
      connectedDesc: 'Track jumps, leaderboards, highlight reel.',
      coffeeLabel: 'Filter coffee',
      coffeeDesc: 'Coffee for the grown-ups while the kids jump.',
      extraPersonLabel: 'Extra person',
      extraPersonDesc: 'Add another jumper to this booking.',
      lockLabel: 'Padlock',
      lockDesc: 'Padlock for the lockers.',
      socksLabel: 'Socks',
      socksDesc: 'Jump socks, required.',
      waterBottleLabel: 'Water bottle',
      waterBottleDesc: 'Add a bottle or confirm you brought your own.',
    },
  },
  skyrider: {
    title: 'Before SkyRider',
    description: 'Check the height requirement and when SkyRider fits best.',
    infoLabel: 'SkyRider information',
    requirementTitle: 'Minimum 125 cm',
    requirementText: 'Everyone riding SkyRider needs to be at least 125 cm tall.',
    timingTitle: 'Best after jump time',
    timingText: 'We recommend doing SkyRider after the jump session.',
    confirmCheckbox: 'I confirm that all SkyRider riders are at least 125 cm.',
    removeSkyRider: 'Remove SkyRider',
  },
  connected: {
    title: 'Connected profiles',
    description: 'Each Connected band is linked to a profile. Enter names so staff know who gets which band.',
    profile: 'Profile',
    namePlaceholder: 'Name',
    avatar: 'Icon',
    confirm: 'Confirm profiles',
  },
  payment: {
    title: 'Payment',
    description: 'Tap your card on the terminal when ready.',
    booking: 'Booking',
    items: "What you're paying for",
    total: 'Total',
    pay: 'Pay',
    afterPaymentHint: 'After payment you continue to the entrance.',
    baseProduct: 'Booking',
    addonsLabel: 'Add-ons',
  },
  confirm: {
    title: 'Ready for entry',
    subtitle: 'Pick up wristbands from staff.',
    onsiteSubtitle: 'Pick up wristbands from staff.',
    smsSubtitle: 'Go to staff when you arrive at the park.',
    kioskSubtitle: 'Take the printout and show it when you pick up wristbands.',
    pickupCode: 'Booking',
    handoffTitle: 'Show at entry',
    handoffCode: 'Handoff code',
    qrHelp: 'Show the QR code to staff. Name or email also works.',
    entryTicketFallback: 'Entry',
    staffHandout: 'To pick up',
    otherAddons: 'Also on your booking',
    wristbands: 'Wristbands',
    connectedBands: 'Connected bands',
    complete: 'Done & next guest',
    done: 'Make a new booking',
    showStaffNote: 'Show staff',
    alreadyCheckedInTitle: 'Already checked in',
    alreadyCheckedInSubtitle: 'This booking has already been completed.',
    alreadyCheckedInHelp: 'Call staff if anything looks wrong.',
  },
  print: {
    title: 'Done, head to the park!',
    subtitle: 'Your receipt is printing.',
    printing: 'Printing…',
  },
  present: {
    eyebrow: 'Show at entrance',
    title: 'Ready for the park',
    instruction: 'Go to staff to get your wristbands.',
    startOver: 'Start over',
  },
  extend: {
    loading: 'Loading extension…',
    view: {
      title: 'Extend your session',
      subtitle: '+30 minutes of extra jump time.',
      currentEnd: 'Current end',
      newEnd: 'New end',
      price: 'Price',
      cta: 'Pay',
    },
    pay: {
      title: 'Extension payment',
      subtitle: '+30 min for',
      swish: 'Swish',
      card: 'Card',
    },
    qr: {
      eyebrow: 'Band swap',
      title: '+30 minutes confirmed',
      newEndPrefix: 'New end:',
      nextStepLabel: 'Next step',
      nextStepText: 'Go to the cashier or staff to get a new wristband with the updated end time.',
    },
    error: {
      title: "We couldn't load the extension",
      expired: 'This link has expired. Please call staff.',
      already: 'This booking has already been extended.',
      generic: 'Something went wrong. Please call staff.',
    },
  },
};

export type Translations = typeof sv;
const translations: Record<Language, Translations> = { sv, en };

interface LanguageContextValue {
  lang: Language;
  t: Translations;
  toggleLang: () => void;
  setLang: (l: Language) => void;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'sv',
  t: sv,
  toggleLang: () => {},
  setLang: () => {},
});

const STORAGE_KEY = 'jy.lang';

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'sv';
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY) as Language | null;
      return stored === 'sv' || stored === 'en' ? stored : 'sv';
    } catch {}
    return 'sv';
  });

  const setLang = (l: Language) => {
    setLangState(l);
    try {
      localStorage.setItem(STORAGE_KEY, l);
    } catch {}
  };
  const toggleLang = () => setLang(lang === 'sv' ? 'en' : 'sv');

  // #350: the document language follows the guest's choice for assistive technology.
  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggleLang, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  return useContext(LanguageContext);
}
